//! Formatting utilities for resolved intents.
//!
//! Provides human-readable rendering of intent resolution output,
//! used by `kodoc intent-explain` to show what an intent resolves to.

use crate::ResolvedIntent;

/// Formats generated code as a human-readable Kōdo source string.
///
/// Used by `kodoc intent-explain` to show what an intent resolves to.
#[must_use]
pub fn format_resolved_intent(resolved: &ResolvedIntent) -> String {
    use std::fmt::Write;
    let mut output = String::new();
    output.push_str("// Generated by intent resolver\n\n");
    output.push_str(&resolved.description);
    output.push_str("\n\n");

    for func in &resolved.generated_functions {
        let _ = write!(output, "fn {}(", func.name);
        for (i, param) in func.params.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            let _ = write!(output, "{}: {:?}", param.name, param.ty);
        }
        let _ = write!(output, ") -> {:?}", func.return_type);

        for req in &func.requires {
            let _ = write!(output, "\n    requires {{ {req:?} }}");
        }

        output.push_str(" {\n    // ... generated body ...\n}\n\n");
    }

    output
}
