//! # kodoc — The Kōdo Compiler
//!
//! The command-line interface for the Kōdo programming language compiler.
//! Designed to be used both by AI agents (with `--emit json-errors`) and
//! humans (with beautiful terminal error messages via ariadne).

mod certificate;
mod diagnostics;
mod explanations;
mod formatter;
mod repl;

use clap::{Parser, Subcommand};
use std::path::PathBuf;

/// The Kōdo compiler — a language built for AI agents, transparent for humans.
#[derive(Parser)]
#[command(name = "kodoc", version, about, long_about = None)]
struct Cli {
    /// Subcommand to execute.
    #[command(subcommand)]
    command: Command,
}

/// Available compiler commands.
#[derive(Subcommand)]
enum Command {
    /// Compile a Kōdo source file to a binary.
    Build {
        /// The source file to compile.
        #[arg()]
        file: PathBuf,

        /// Output file path.
        #[arg(short, long)]
        output: Option<PathBuf>,

        /// Emit errors as JSON (for AI agent consumption).
        #[arg(long, default_value_t = false)]
        json_errors: bool,

        /// Contract checking mode: static, runtime, both, none.
        #[arg(long, default_value = "runtime")]
        contracts: String,

        /// Print the MIR (Mid-level IR) to stdout before code generation.
        #[arg(long, default_value_t = false)]
        emit_mir: bool,
    },
    /// Lower a source file to MIR and print it without generating code.
    Mir {
        /// The source file to lower.
        #[arg()]
        file: PathBuf,

        /// Contract checking mode: static, runtime, both, none.
        #[arg(long, default_value = "runtime")]
        contracts: String,
    },
    /// Type-check and verify contracts without generating code.
    Check {
        /// The source file to check.
        #[arg()]
        file: PathBuf,

        /// Emit errors as JSON.
        #[arg(long, default_value_t = false)]
        json_errors: bool,

        /// Contract checking mode: static, runtime, both, none.
        #[arg(long, default_value = "runtime")]
        contracts: String,
    },
    /// Tokenize a source file and print the token stream.
    Lex {
        /// The source file to tokenize.
        #[arg()]
        file: PathBuf,
    },
    /// Parse a source file and print the AST.
    Parse {
        /// The source file to parse.
        #[arg()]
        file: PathBuf,
    },
    /// Explain an error code in detail with examples.
    Explain {
        /// The error code to explain (e.g., E0200).
        #[arg()]
        code: String,
    },
    /// Format a Kōdo source file.
    Fmt {
        /// The source file to format.
        #[arg()]
        file: PathBuf,

        /// Check formatting without modifying the file.
        #[arg(long, default_value_t = false)]
        check: bool,
    },
    /// Show the code generated by intent resolution.
    IntentExplain {
        /// The source file containing intents.
        #[arg()]
        file: PathBuf,
    },
    /// Start the Kōdo Language Server Protocol server.
    Lsp,
    /// Start an interactive REPL (Read-Eval-Print Loop).
    Repl,
    /// Generate a confidence report for a module.
    ConfidenceReport {
        /// The source file to analyze.
        #[arg()]
        file: PathBuf,

        /// Output as JSON instead of human-readable table.
        #[arg(long, default_value_t = false)]
        json: bool,

        /// Confidence threshold — functions below this value are flagged (0.0–1.0).
        #[arg(long, default_value_t = 0.8)]
        threshold: f64,
    },
    /// Apply auto-fix patches to resolve compiler errors.
    Fix {
        /// The source file to fix.
        #[arg()]
        file: PathBuf,

        /// Show patches without applying them.
        #[arg(long, default_value_t = false)]
        dry_run: bool,
    },
    /// Inspect metadata embedded in a compiled Kōdo binary.
    Describe {
        /// The compiled binary to inspect.
        #[arg()]
        binary: PathBuf,

        /// Output as raw JSON instead of human-readable format.
        #[arg(long, default_value_t = false)]
        json: bool,
    },
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("warn")),
        )
        .init();

    let cli = Cli::parse();

    let exit_code = match cli.command {
        Command::Build {
            file,
            output,
            json_errors,
            contracts,
            emit_mir,
        } => run_build(&file, output.as_deref(), json_errors, &contracts, emit_mir),
        Command::Mir { file, contracts } => run_mir(&file, &contracts),
        Command::Check {
            file,
            json_errors,
            contracts,
        } => run_check(&file, json_errors, &contracts),
        Command::Lex { file } => run_lex(&file),
        Command::Parse { file } => run_parse(&file),
        Command::Explain { code } => run_explain(&code),
        Command::Fmt { file, check } => run_fmt(&file, check),
        Command::IntentExplain { file } => run_intent_explain(&file),
        Command::Lsp => run_lsp(),
        Command::Repl => repl::run_repl(),
        Command::ConfidenceReport {
            file,
            json,
            threshold,
        } => run_confidence_report(&file, json, threshold),
        Command::Fix { file, dry_run } => run_fix(&file, dry_run),
        Command::Describe { binary, json } => run_describe(&binary, json),
    };

    std::process::exit(exit_code);
}

/// Parses a `--contracts` flag value into a [`kodo_contracts::ContractMode`].
fn parse_contract_mode(value: &str) -> kodo_contracts::ContractMode {
    match value.to_lowercase().as_str() {
        "static" => kodo_contracts::ContractMode::Static,
        "runtime" => kodo_contracts::ContractMode::Runtime,
        "both" => kodo_contracts::ContractMode::Both,
        "none" => kodo_contracts::ContractMode::None,
        _ => {
            eprintln!("warning: unknown contract mode `{value}`, falling back to `runtime`");
            kodo_contracts::ContractMode::Runtime
        }
    }
}

fn run_build(
    file: &PathBuf,
    output: Option<&std::path::Path>,
    json_errors: bool,
    contracts_mode_str: &str,
    emit_mir: bool,
) -> i32 {
    tracing::info!("building {}", file.display());

    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let filename = file.display().to_string();

    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            if json_errors {
                diagnostics::render_parse_error_json(&source, &filename, &e);
            } else {
                diagnostics::render_parse_error(&source, &filename, &e);
            }
            return 1;
        }
    };

    // Process imports — compile imported modules and collect their types/functions.
    let base_dir = file.parent().unwrap_or_else(|| std::path::Path::new("."));
    let mut imported_object_files: Vec<std::path::PathBuf> = Vec::new();
    let mut imported_modules: Vec<kodo_ast::Module> = Vec::new();

    // Detect import cycles.
    let mut visited = std::collections::HashSet::new();
    if let Ok(canonical) = file.canonicalize() {
        visited.insert(canonical);
    }
    if let Err(msg) = check_import_cycles(base_dir, &module, &mut visited, file) {
        eprintln!("{msg}");
        return 1;
    }

    for import in &module.imports {
        let import_path = resolve_import_path(base_dir, &import.path);
        match compile_imported_module(&import_path, &mut imported_object_files) {
            Ok(imported_module) => imported_modules.push(imported_module),
            Err(msg) => {
                eprintln!("{msg}");
                return 1;
            }
        }
    }

    // Load stdlib prelude modules (Option, Result).
    let mut prelude_modules = Vec::new();
    for (_name, source) in kodo_std::prelude_sources() {
        match kodo_parser::parse(source) {
            Ok(m) => prelude_modules.push(m),
            Err(e) => {
                eprintln!("stdlib parse error: {e}");
                return 1;
            }
        }
    }

    // Type check — register prelude, imports, then user module.
    let mut checker = kodo_types::TypeChecker::new();
    for prelude in &prelude_modules {
        if let Err(e) = checker.check_module(prelude) {
            eprintln!("stdlib type error: {e}");
            return 1;
        }
    }
    for imported in &imported_modules {
        if let Err(e) = checker.check_module(imported) {
            eprintln!("type error in imported module `{}`: {e}", imported.name);
            return 1;
        }
    }
    let type_errors = checker.check_module_collecting(&module);
    if !type_errors.is_empty() {
        for e in &type_errors {
            if json_errors {
                diagnostics::render_type_error_json(&source, &filename, e);
            } else {
                diagnostics::render_type_error(&source, &filename, e);
            }
        }
        return 1;
    }

    // Contract verification
    let contract_mode = parse_contract_mode(contracts_mode_str);
    for func in &module.functions {
        let contracts = kodo_contracts::extract_contracts(func);
        if let Err(e) = kodo_contracts::verify_contracts(&contracts, contract_mode) {
            eprintln!("contract error: {e}");
            return 1;
        }
    }
    for impl_block in &module.impl_blocks {
        for method in &impl_block.methods {
            let contracts = kodo_contracts::extract_contracts(method);
            if let Err(e) = kodo_contracts::verify_contracts(&contracts, contract_mode) {
                eprintln!("contract error: {e}");
                return 1;
            }
        }
    }

    // Intent resolution — resolve intent blocks into concrete code.
    let mut module = module;
    if !module.intent_decls.is_empty() {
        let resolver = kodo_resolver::Resolver::with_builtins();
        match resolver.resolve_all(&module.intent_decls) {
            Ok(resolved_intents) => {
                for resolved in resolved_intents {
                    // Skip generated functions that already exist in the module
                    // (the intent serves as a declaration of intent, not a replacement).
                    for func in resolved.generated_functions {
                        let already_exists = module.functions.iter().any(|f| f.name == func.name);
                        if !already_exists {
                            module.functions.push(func);
                        }
                    }
                }
            }
            Err(e) => {
                eprintln!("resolver error: {e}");
                return 1;
            }
        }
    }

    // Desugar pass — simplify syntactic sugar (e.g. for loops) before MIR lowering.
    kodo_desugar::desugar_module(&mut module);

    // Transform impl block methods into top-level functions with mangled names.
    for impl_block in &module.impl_blocks {
        for method in &impl_block.methods {
            let mut func = method.clone();
            func.name = format!("{}_{}", impl_block.type_name, method.name);
            // Ensure self param has the correct type
            for param in &mut func.params {
                if param.name == "self" {
                    param.ty = kodo_ast::TypeExpr::Named(impl_block.type_name.clone());
                }
            }
            module.functions.push(func);
        }
    }

    // Rewrite method calls in the AST: `obj.method(args)` → `TypeName_method(obj, args)`
    // Uses span-based resolutions from the type checker to precisely identify method calls.
    let method_resolutions = checker.method_resolutions().clone();
    if !method_resolutions.is_empty() {
        for func in &mut module.functions {
            rewrite_method_calls_in_block(&mut func.body, &method_resolutions);
        }
        // Also rewrite method calls inside actor handler bodies so that
        // handler-to-handler calls and self-calls are properly mangled.
        for actor_decl in &mut module.actor_decls {
            for handler in &mut actor_decl.handlers {
                rewrite_method_calls_in_block(&mut handler.body, &method_resolutions);
            }
        }
    }

    // Generate monomorphized function instances from generic functions.
    let mut generated_fns: std::collections::HashSet<String> = std::collections::HashSet::new();
    for (base_name, type_args, mono_name) in checker.fn_instances() {
        if generated_fns.contains(mono_name) {
            continue;
        }
        generated_fns.insert(mono_name.clone());
        if let Some(generic_fn) = module
            .functions
            .iter()
            .find(|f| f.name == *base_name)
            .cloned()
        {
            let subst: std::collections::HashMap<String, kodo_ast::TypeExpr> = generic_fn
                .generic_params
                .iter()
                .zip(type_args)
                .map(|(param, ty)| (param.clone(), type_to_type_expr(ty)))
                .collect();
            let mut mono_fn = generic_fn;
            mono_fn.name = mono_name.clone();
            mono_fn.generic_params = vec![];
            for param in &mut mono_fn.params {
                param.ty = substitute_type_expr_ast(&param.ty, &subst);
            }
            mono_fn.return_type = substitute_type_expr_ast(&mono_fn.return_type, &subst);
            module.functions.push(mono_fn);
        }
    }

    // MIR lowering — combine all modules' functions.
    let mut all_mir_functions = Vec::new();

    // Lower imported modules first.
    for imported in &imported_modules {
        match kodo_mir::lowering::lower_module_with_type_info(
            imported,
            checker.struct_registry(),
            checker.enum_registry(),
            checker.enum_names(),
            checker.type_alias_registry(),
        ) {
            Ok(fns) => all_mir_functions.extend(fns),
            Err(e) => {
                eprintln!("MIR lowering error in imported module: {e}");
                return 1;
            }
        }
    }

    // Lower the main module.
    let mir_functions = match kodo_mir::lowering::lower_module_with_type_info(
        &module,
        checker.struct_registry(),
        checker.enum_registry(),
        checker.enum_names(),
        checker.type_alias_registry(),
    ) {
        Ok(fns) => fns,
        Err(e) => {
            eprintln!("MIR lowering error: {e}");
            return 1;
        }
    };
    all_mir_functions.extend(mir_functions);

    // Run MIR optimization passes (inlining, constant folding, DCE, copy propagation).
    kodo_mir::optimize::optimize_all(&mut all_mir_functions);

    // Print MIR to stdout if --emit-mir was requested.
    if emit_mir {
        println!("--- MIR ({} functions) ---", all_mir_functions.len());
        for func in &all_mir_functions {
            println!("{func:#?}");
            println!();
        }
        println!("--- end MIR ---");
    }

    // Build module metadata for embedding in the binary.
    let metadata_json = build_module_metadata(&module);

    // Use type checker registries for codegen (includes monomorphized generics).
    let struct_defs: std::collections::HashMap<String, Vec<(String, kodo_types::Type)>> =
        checker.struct_registry().clone();
    let enum_defs: std::collections::HashMap<String, Vec<(String, Vec<kodo_types::Type>)>> =
        checker.enum_registry().clone();

    // Code generation
    let options = kodo_codegen::CodegenOptions::default();
    let object_bytes = match kodo_codegen::compile_module_with_types(
        &all_mir_functions,
        &struct_defs,
        &enum_defs,
        &options,
        Some(&metadata_json),
    ) {
        Ok(bytes) => bytes,
        Err(e) => {
            eprintln!("codegen error: {e}");
            return 1;
        }
    };

    // Determine output path
    let output_path = output
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| file.with_extension(""));

    // Write object file to a temporary location
    let obj_path = output_path.with_extension("o");
    if let Err(e) = std::fs::write(&obj_path, &object_bytes) {
        eprintln!("error: could not write object file: {e}");
        return 1;
    }

    // Link with the runtime
    let link_result = link_executable(&obj_path, &output_path);

    // Clean up the .o file
    let _ = std::fs::remove_file(&obj_path);

    match link_result {
        Ok(()) => {
            // Read the binary for hashing.
            let binary_bytes = std::fs::read(&output_path).ok();

            // Read previous certificate if it exists (for chaining).
            let cert_path = output_path.with_extension("ko.cert.json");
            let parent_cert = std::fs::read_to_string(&cert_path).ok().and_then(|json| {
                serde_json::from_str::<certificate::CompilationCertificate>(&json).ok()
            });

            // Emit compilation certificate.
            let cert = certificate::CompilationCertificate::from_module(
                &module,
                &source,
                binary_bytes.as_deref(),
                parent_cert.as_ref(),
            );
            match cert.to_json() {
                Ok(json) => {
                    if let Err(e) = std::fs::write(&cert_path, &json) {
                        eprintln!("warning: could not write certificate: {e}");
                    }
                }
                Err(e) => {
                    eprintln!("warning: {e}");
                }
            }

            println!(
                "Successfully compiled `{}` → {}",
                module.name,
                output_path.display()
            );
            0
        }
        Err(e) => {
            eprintln!("link error: {e}");
            1
        }
    }
}

/// Reads and displays module metadata from a compiled Kōdo binary.
fn run_describe(binary: &PathBuf, json_output: bool) -> i32 {
    let data = match std::fs::read(binary) {
        Ok(d) => d,
        Err(e) => {
            eprintln!("error: could not read binary `{}`: {e}", binary.display());
            return 1;
        }
    };

    let file = match object::File::parse(&*data) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("error: could not parse binary `{}`: {e}", binary.display());
            return 1;
        }
    };

    let meta_bytes = find_kodo_meta(&file, &data);

    match meta_bytes {
        Some(json_str) => {
            if json_output {
                println!("{json_str}");
            } else {
                print_metadata_human(&json_str);
            }
            0
        }
        None => {
            eprintln!("error: no Kōdo metadata found in `{}`", binary.display());
            eprintln!("hint: was this binary compiled with kodoc?");
            1
        }
    }
}

/// Finds the `kodo_meta` content in the binary by looking for the exported data symbols.
fn find_kodo_meta(file: &object::File, _data: &[u8]) -> Option<String> {
    use object::{Object, ObjectSection, ObjectSymbol};

    // Try to find kodo_meta and kodo_meta_len symbols
    let mut meta_addr = None;
    let mut meta_len_addr = None;

    for symbol in file.symbols() {
        let name = symbol.name().unwrap_or("");
        // On macOS, symbols have a leading underscore
        let clean_name = name.strip_prefix('_').unwrap_or(name);
        match clean_name {
            "kodo_meta" => meta_addr = Some((symbol.address(), symbol.size())),
            "kodo_meta_len" => meta_len_addr = Some((symbol.address(), symbol.size())),
            _ => {}
        }
    }

    let (meta_address, meta_symbol_size) = meta_addr?;
    let (len_address, _) = meta_len_addr?;

    // Find the section containing the metadata length
    for section in file.sections() {
        let section_addr = section.address();
        let section_data = section.data().ok()?;

        // Check if kodo_meta_len is in this section
        if len_address >= section_addr && len_address < section_addr + section_data.len() as u64 {
            let len_offset = (len_address - section_addr) as usize;
            if len_offset + 8 <= section_data.len() {
                let len_bytes: [u8; 8] =
                    section_data[len_offset..len_offset + 8].try_into().ok()?;
                let meta_len = u64::from_le_bytes(len_bytes) as usize;

                // Now find kodo_meta data in same section
                if meta_address >= section_addr
                    && meta_address < section_addr + section_data.len() as u64
                {
                    let meta_offset = (meta_address - section_addr) as usize;
                    if meta_offset + meta_len <= section_data.len() {
                        let meta_str =
                            std::str::from_utf8(&section_data[meta_offset..meta_offset + meta_len])
                                .ok()?;
                        return Some(meta_str.to_string());
                    }
                }

                // Meta might be in a different section
                for other_section in file.sections() {
                    let other_addr = other_section.address();
                    let other_data = other_section.data().ok()?;
                    if meta_address >= other_addr
                        && meta_address < other_addr + other_data.len() as u64
                    {
                        let meta_offset = (meta_address - other_addr) as usize;
                        if meta_offset + meta_len <= other_data.len() {
                            let meta_str = std::str::from_utf8(
                                &other_data[meta_offset..meta_offset + meta_len],
                            )
                            .ok()?;
                            return Some(meta_str.to_string());
                        }
                    }
                }
            }
        }
    }

    // Fallback: try using symbol size directly
    if meta_symbol_size > 0 {
        for section in file.sections() {
            let section_addr = section.address();
            let section_data = section.data().ok()?;
            if meta_address >= section_addr
                && meta_address < section_addr + section_data.len() as u64
            {
                let meta_offset = (meta_address - section_addr) as usize;
                let meta_len = meta_symbol_size as usize;
                if meta_offset + meta_len <= section_data.len() {
                    let meta_str =
                        std::str::from_utf8(&section_data[meta_offset..meta_offset + meta_len])
                            .ok()?;
                    return Some(meta_str.to_string());
                }
            }
        }
    }

    None
}

/// Prints metadata in a human-readable format.
fn print_metadata_human(json_str: &str) {
    match serde_json::from_str::<serde_json::Value>(json_str) {
        Ok(value) => {
            println!("Kōdo Module Metadata");
            println!("{}", "=".repeat(40));
            if let Some(obj) = value.as_object() {
                for (key, val) in obj {
                    match val {
                        serde_json::Value::String(s) => println!("  {key}: {s}"),
                        serde_json::Value::Array(arr) => {
                            println!("  {key}:");
                            for item in arr {
                                if let serde_json::Value::String(s) = item {
                                    println!("    - {s}");
                                } else {
                                    println!("    - {item}");
                                }
                            }
                        }
                        other => println!("  {key}: {other}"),
                    }
                }
            }
        }
        Err(_) => {
            // If not valid JSON, just print raw
            println!("{json_str}");
        }
    }
}

/// Rewrites method calls in a block by replacing `obj.method(args)` with
/// `TypeName_method(obj, args)` where a method call was resolved during type checking.
fn rewrite_method_calls_in_block(
    block: &mut kodo_ast::Block,
    resolutions: &std::collections::HashMap<u32, String>,
) {
    for stmt in &mut block.stmts {
        match stmt {
            kodo_ast::Stmt::Let { value, .. } | kodo_ast::Stmt::Assign { value, .. } => {
                *value = rewrite_method_calls_in_expr(
                    std::mem::replace(value, kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0))),
                    resolutions,
                );
            }
            kodo_ast::Stmt::Expr(expr) => {
                *expr = rewrite_method_calls_in_expr(
                    std::mem::replace(expr, kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0))),
                    resolutions,
                );
            }
            kodo_ast::Stmt::Return { value, .. } => {
                if let Some(v) = value {
                    *v = rewrite_method_calls_in_expr(
                        std::mem::replace(v, kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0))),
                        resolutions,
                    );
                }
            }
            kodo_ast::Stmt::While {
                condition, body, ..
            } => {
                *condition = rewrite_method_calls_in_expr(
                    std::mem::replace(
                        condition,
                        kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0)),
                    ),
                    resolutions,
                );
                rewrite_method_calls_in_block(body, resolutions);
            }
            kodo_ast::Stmt::For {
                start, end, body, ..
            } => {
                *start = rewrite_method_calls_in_expr(
                    std::mem::replace(start, kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0))),
                    resolutions,
                );
                *end = rewrite_method_calls_in_expr(
                    std::mem::replace(end, kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0))),
                    resolutions,
                );
                rewrite_method_calls_in_block(body, resolutions);
            }
            kodo_ast::Stmt::IfLet {
                value,
                body,
                else_body,
                ..
            } => {
                *value = rewrite_method_calls_in_expr(
                    std::mem::replace(value, kodo_ast::Expr::IntLit(0, kodo_ast::Span::new(0, 0))),
                    resolutions,
                );
                rewrite_method_calls_in_block(body, resolutions);
                if let Some(eb) = else_body {
                    rewrite_method_calls_in_block(eb, resolutions);
                }
            }
            kodo_ast::Stmt::Spawn { body, .. } => {
                rewrite_method_calls_in_block(body, resolutions);
            }
            kodo_ast::Stmt::Parallel { body, .. } => {
                for stmt in body {
                    if let kodo_ast::Stmt::Spawn { body, .. } = stmt {
                        rewrite_method_calls_in_block(body, resolutions);
                    }
                }
            }
        }
    }
}

/// Rewrites method calls in an expression. Uses span-based resolutions from the
/// type checker to detect `Call { callee: FieldAccess { object, field }, args }`
/// and rewrites to `Call { callee: Ident(mangled), args: [object, ...args] }`.
fn rewrite_method_calls_in_expr(
    expr: kodo_ast::Expr,
    resolutions: &std::collections::HashMap<u32, String>,
) -> kodo_ast::Expr {
    match expr {
        kodo_ast::Expr::Call { callee, args, span } => {
            if let kodo_ast::Expr::FieldAccess {
                object,
                field,
                span: fa_span,
            } = *callee
            {
                // Rewrite sub-expressions first
                let object = rewrite_method_calls_in_expr(*object, resolutions);
                let args: Vec<_> = args
                    .into_iter()
                    .map(|a| rewrite_method_calls_in_expr(a, resolutions))
                    .collect();

                // Check if this call span was resolved as a method call
                if let Some(mangled) = resolutions.get(&span.start) {
                    let mut new_args = vec![object];
                    new_args.extend(args);
                    return kodo_ast::Expr::Call {
                        callee: Box::new(kodo_ast::Expr::Ident(mangled.clone(), span)),
                        args: new_args,
                        span,
                    };
                }

                // Not a method call — reconstruct as FieldAccess + Call
                kodo_ast::Expr::Call {
                    callee: Box::new(kodo_ast::Expr::FieldAccess {
                        object: Box::new(object),
                        field,
                        span: fa_span,
                    }),
                    args,
                    span,
                }
            } else {
                let callee = rewrite_method_calls_in_expr(*callee, resolutions);
                let args: Vec<_> = args
                    .into_iter()
                    .map(|a| rewrite_method_calls_in_expr(a, resolutions))
                    .collect();
                kodo_ast::Expr::Call {
                    callee: Box::new(callee),
                    args,
                    span,
                }
            }
        }
        kodo_ast::Expr::BinaryOp {
            left,
            op,
            right,
            span,
        } => kodo_ast::Expr::BinaryOp {
            left: Box::new(rewrite_method_calls_in_expr(*left, resolutions)),
            op,
            right: Box::new(rewrite_method_calls_in_expr(*right, resolutions)),
            span,
        },
        kodo_ast::Expr::UnaryOp { op, operand, span } => kodo_ast::Expr::UnaryOp {
            op,
            operand: Box::new(rewrite_method_calls_in_expr(*operand, resolutions)),
            span,
        },
        kodo_ast::Expr::If {
            condition,
            mut then_branch,
            else_branch,
            span,
        } => {
            let condition = rewrite_method_calls_in_expr(*condition, resolutions);
            rewrite_method_calls_in_block(&mut then_branch, resolutions);
            let else_branch = else_branch.map(|mut b| {
                rewrite_method_calls_in_block(&mut b, resolutions);
                b
            });
            kodo_ast::Expr::If {
                condition: Box::new(condition),
                then_branch,
                else_branch,
                span,
            }
        }
        kodo_ast::Expr::FieldAccess {
            object,
            field,
            span,
        } => kodo_ast::Expr::FieldAccess {
            object: Box::new(rewrite_method_calls_in_expr(*object, resolutions)),
            field,
            span,
        },
        kodo_ast::Expr::StructLit { name, fields, span } => kodo_ast::Expr::StructLit {
            name,
            fields: fields
                .into_iter()
                .map(|f| kodo_ast::FieldInit {
                    name: f.name,
                    value: rewrite_method_calls_in_expr(f.value, resolutions),
                    span: f.span,
                })
                .collect(),
            span,
        },
        kodo_ast::Expr::EnumVariantExpr {
            enum_name,
            variant,
            args,
            span,
        } => kodo_ast::Expr::EnumVariantExpr {
            enum_name,
            variant,
            args: args
                .into_iter()
                .map(|a| rewrite_method_calls_in_expr(a, resolutions))
                .collect(),
            span,
        },
        kodo_ast::Expr::Match { expr, arms, span } => kodo_ast::Expr::Match {
            expr: Box::new(rewrite_method_calls_in_expr(*expr, resolutions)),
            arms: arms
                .into_iter()
                .map(|arm| kodo_ast::MatchArm {
                    pattern: arm.pattern,
                    body: rewrite_method_calls_in_expr(arm.body, resolutions),
                    span: arm.span,
                })
                .collect(),
            span,
        },
        kodo_ast::Expr::Block(mut block) => {
            rewrite_method_calls_in_block(&mut block, resolutions);
            kodo_ast::Expr::Block(block)
        }
        kodo_ast::Expr::Closure {
            params,
            return_type,
            body,
            span,
        } => kodo_ast::Expr::Closure {
            params,
            return_type,
            body: Box::new(rewrite_method_calls_in_expr(*body, resolutions)),
            span,
        },
        kodo_ast::Expr::NullCoalesce { left, right, span } => kodo_ast::Expr::NullCoalesce {
            left: Box::new(rewrite_method_calls_in_expr(*left, resolutions)),
            right: Box::new(rewrite_method_calls_in_expr(*right, resolutions)),
            span,
        },
        kodo_ast::Expr::Try { operand, span } => kodo_ast::Expr::Try {
            operand: Box::new(rewrite_method_calls_in_expr(*operand, resolutions)),
            span,
        },
        kodo_ast::Expr::OptionalChain {
            object,
            field,
            span,
        } => kodo_ast::Expr::OptionalChain {
            object: Box::new(rewrite_method_calls_in_expr(*object, resolutions)),
            field,
            span,
        },
        kodo_ast::Expr::Range {
            start,
            end,
            inclusive,
            span,
        } => kodo_ast::Expr::Range {
            start: Box::new(rewrite_method_calls_in_expr(*start, resolutions)),
            end: Box::new(rewrite_method_calls_in_expr(*end, resolutions)),
            inclusive,
            span,
        },
        kodo_ast::Expr::Is {
            operand,
            type_name,
            span,
        } => kodo_ast::Expr::Is {
            operand: Box::new(rewrite_method_calls_in_expr(*operand, resolutions)),
            type_name,
            span,
        },
        kodo_ast::Expr::Await { operand, span } => kodo_ast::Expr::Await {
            operand: Box::new(rewrite_method_calls_in_expr(*operand, resolutions)),
            span,
        },
        // Leaf expressions — no sub-expressions to rewrite
        e @ (kodo_ast::Expr::IntLit(_, _)
        | kodo_ast::Expr::FloatLit(_, _)
        | kodo_ast::Expr::StringLit(_, _)
        | kodo_ast::Expr::BoolLit(_, _)
        | kodo_ast::Expr::Ident(_, _)) => e,
    }
}

/// Converts a [`kodo_types::Type`] to a [`kodo_ast::TypeExpr`].
fn type_to_type_expr(ty: &kodo_types::Type) -> kodo_ast::TypeExpr {
    match ty {
        kodo_types::Type::Int => kodo_ast::TypeExpr::Named("Int".to_string()),
        kodo_types::Type::Bool => kodo_ast::TypeExpr::Named("Bool".to_string()),
        kodo_types::Type::String => kodo_ast::TypeExpr::Named("String".to_string()),
        kodo_types::Type::Unit => kodo_ast::TypeExpr::Unit,
        kodo_types::Type::Struct(name) | kodo_types::Type::Enum(name) => {
            kodo_ast::TypeExpr::Named(name.clone())
        }
        _ => kodo_ast::TypeExpr::Named("Unknown".to_string()),
    }
}

/// Substitutes type parameters in a [`kodo_ast::TypeExpr`].
fn substitute_type_expr_ast(
    expr: &kodo_ast::TypeExpr,
    subst: &std::collections::HashMap<String, kodo_ast::TypeExpr>,
) -> kodo_ast::TypeExpr {
    match expr {
        kodo_ast::TypeExpr::Named(name) => {
            if let Some(replacement) = subst.get(name) {
                replacement.clone()
            } else {
                expr.clone()
            }
        }
        kodo_ast::TypeExpr::Generic(name, args) => kodo_ast::TypeExpr::Generic(
            name.clone(),
            args.iter()
                .map(|a| substitute_type_expr_ast(a, subst))
                .collect(),
        ),
        kodo_ast::TypeExpr::Function(params, ret) => kodo_ast::TypeExpr::Function(
            params
                .iter()
                .map(|p| substitute_type_expr_ast(p, subst))
                .collect(),
            Box::new(substitute_type_expr_ast(ret, subst)),
        ),
        kodo_ast::TypeExpr::Unit => kodo_ast::TypeExpr::Unit,
        kodo_ast::TypeExpr::Optional(inner) => {
            kodo_ast::TypeExpr::Optional(Box::new(substitute_type_expr_ast(inner, subst)))
        }
    }
}

/// Resolves an import path to a `.ko` file path.
///
/// Tries `<base_dir>/<segments>.ko` first, then `<base_dir>/<segments>/lib.ko`.
///
/// `import math.utils` resolves to `<base_dir>/math/utils.ko`
/// or `<base_dir>/math/utils/lib.ko`.
fn resolve_import_path(base_dir: &std::path::Path, segments: &[String]) -> std::path::PathBuf {
    let mut path = base_dir.to_path_buf();
    for segment in segments {
        path.push(segment);
    }
    path.set_extension("ko");

    // Try lib.ko fallback if the direct path doesn't exist.
    if !path.exists() {
        let mut alt_path = base_dir.to_path_buf();
        for segment in segments {
            alt_path.push(segment);
        }
        alt_path.push("lib.ko");
        if alt_path.exists() {
            return alt_path;
        }
    }

    path
}

/// Compiles an imported module and returns its parsed AST.
///
/// Checks for import cycles using the `visited` set. Returns an error
/// if a cycle is detected.
fn compile_imported_module(
    path: &std::path::Path,
    _object_files: &mut Vec<std::path::PathBuf>,
) -> std::result::Result<kodo_ast::Module, String> {
    let source = std::fs::read_to_string(path).map_err(|_| {
        let mut msg = format!("error: unresolved import `{}`", path.display());
        // Suggest similar .ko files in the same directory.
        if let Some(parent) = path.parent() {
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                if let Ok(entries) = std::fs::read_dir(parent) {
                    let candidates: Vec<String> = entries
                        .filter_map(|e| e.ok())
                        .filter_map(|e| {
                            let name = e.file_name();
                            let name_str = name.to_str()?;
                            if name_str.ends_with(".ko") {
                                Some(name_str.trim_end_matches(".ko").to_string())
                            } else {
                                None
                            }
                        })
                        .collect();
                    if let Some(suggestion) = find_similar_import(stem, &candidates) {
                        msg.push_str(&format!("\n  hint: did you mean `{suggestion}`?"));
                    }
                }
            }
        }
        msg
    })?;
    let module = kodo_parser::parse(&source)
        .map_err(|e| format!("parse error in `{}`: {e}", path.display()))?;
    Ok(module)
}

/// Finds the most similar import name using Levenshtein distance.
fn find_similar_import(name: &str, candidates: &[String]) -> Option<String> {
    let threshold = std::cmp::max(name.len() / 2, 3);
    let mut best: Option<(usize, String)> = None;
    for candidate in candidates {
        let dist = strsim::levenshtein(name, candidate);
        if dist > 0 && dist <= threshold && best.as_ref().is_none_or(|(d, _)| dist < *d) {
            best = Some((dist, candidate.clone()));
        }
    }
    best.map(|(_, n)| n)
}

/// Checks for import cycles by detecting if a file imports itself transitively.
fn check_import_cycles(
    base_dir: &std::path::Path,
    module: &kodo_ast::Module,
    visited: &mut std::collections::HashSet<std::path::PathBuf>,
    current_path: &std::path::Path,
) -> std::result::Result<(), String> {
    for import in &module.imports {
        let import_path = resolve_import_path(base_dir, &import.path);
        let canonical = import_path
            .canonicalize()
            .unwrap_or_else(|_| import_path.clone());
        if !visited.insert(canonical.clone()) {
            return Err(format!(
                "error: import cycle detected: `{}` is imported transitively from `{}`",
                import_path.display(),
                current_path.display()
            ));
        }
        // Recursively check the imported module for cycles.
        if let Ok(source) = std::fs::read_to_string(&import_path) {
            if let Ok(imported) = kodo_parser::parse(&source) {
                let imported_base = import_path
                    .parent()
                    .unwrap_or_else(|| std::path::Path::new("."));
                check_import_cycles(imported_base, &imported, visited, &import_path)?;
            }
        }
    }
    Ok(())
}

/// Links an object file with the Kōdo runtime to produce an executable.
fn link_executable(
    obj_path: &std::path::Path,
    output_path: &std::path::Path,
) -> std::result::Result<(), String> {
    // Find the runtime library.
    // Strategy: look relative to the kodoc binary, then in the workspace target dir.
    let runtime_path = find_runtime_lib()?;

    let mut cmd = std::process::Command::new("cc");
    cmd.arg(obj_path)
        .arg(&runtime_path)
        .arg("-o")
        .arg(output_path);

    // On macOS, Cranelift object files lack LC_BUILD_VERSION metadata,
    // producing harmless linker warnings. Suppress them.
    if cfg!(target_os = "macos") {
        cmd.arg("-Wl,-w");
    }

    let status = cmd
        .status()
        .map_err(|e| format!("failed to invoke linker `cc`: {e}"))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "linker failed with exit code {}",
            status.code().unwrap_or(-1)
        ))
    }
}

/// Locates `libkodo_runtime.a` by searching common paths.
fn find_runtime_lib() -> std::result::Result<PathBuf, String> {
    // 1. Check KODO_RUNTIME_LIB env var
    if let Ok(path) = std::env::var("KODO_RUNTIME_LIB") {
        let p = PathBuf::from(path);
        if p.exists() {
            return Ok(p);
        }
    }

    // 2. Check relative to the current executable (workspace target/debug/)
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let candidate = dir.join("libkodo_runtime.a");
            if candidate.exists() {
                return Ok(candidate);
            }
        }
    }

    // 3. Check common cargo target directories
    let candidates = [
        "target/debug/libkodo_runtime.a",
        "target/release/libkodo_runtime.a",
    ];
    for candidate in &candidates {
        let p = PathBuf::from(candidate);
        if p.exists() {
            return Ok(p);
        }
    }

    Err(
        "could not find libkodo_runtime.a — build the workspace first with `cargo build`"
            .to_string(),
    )
}

/// Builds a JSON string with module metadata for embedding in the binary.
fn build_module_metadata(module: &kodo_ast::Module) -> String {
    let meta = module.meta.as_ref();
    let purpose = meta
        .and_then(|m| m.entries.iter().find(|e| e.key == "purpose"))
        .map_or_else(String::new, |e| e.value.clone());
    let version = meta
        .and_then(|m| m.entries.iter().find(|e| e.key == "version"))
        .map_or_else(String::new, |e| e.value.clone());

    let mut functions = Vec::new();
    let mut validators = Vec::new();
    for func in &module.functions {
        let params: Vec<serde_json::Value> = func
            .params
            .iter()
            .map(|p| {
                serde_json::json!({
                    "name": p.name,
                    "type": format!("{:?}", p.ty),
                })
            })
            .collect();

        let requires: Vec<String> = func
            .requires
            .iter()
            .enumerate()
            .map(|(i, _)| format!("requires clause {}", i + 1))
            .collect();

        let ensures: Vec<String> = func
            .ensures
            .iter()
            .enumerate()
            .map(|(i, _)| format!("ensures clause {}", i + 1))
            .collect();

        let mut annotations = serde_json::Map::new();
        for ann in &func.annotations {
            let value = match ann.args.first() {
                Some(kodo_ast::AnnotationArg::Positional(kodo_ast::Expr::IntLit(n, _))) => {
                    serde_json::json!(n)
                }
                Some(kodo_ast::AnnotationArg::Positional(kodo_ast::Expr::StringLit(s, _))) => {
                    serde_json::json!(s)
                }
                Some(kodo_ast::AnnotationArg::Named(_, kodo_ast::Expr::StringLit(s, _))) => {
                    serde_json::json!(s)
                }
                _ => serde_json::json!(true),
            };
            annotations.insert(ann.name.clone(), value);
        }

        functions.push(serde_json::json!({
            "name": func.name,
            "params": params,
            "return_type": format!("{:?}", func.return_type),
            "requires": requires,
            "ensures": ensures,
            "annotations": annotations,
        }));

        if !func.requires.is_empty() {
            validators.push(format!("validate_{}", func.name));
        }
    }

    let metadata = serde_json::json!({
        "module": module.name,
        "purpose": purpose,
        "version": version,
        "compiler_version": env!("CARGO_PKG_VERSION"),
        "functions": functions,
        "validators": validators,
    });

    // This can only fail on non-UTF-8 data which we don't have.
    serde_json::to_string_pretty(&metadata).unwrap_or_default()
}

fn run_mir(file: &PathBuf, contracts_mode_str: &str) -> i32 {
    tracing::info!("lowering to MIR: {}", file.display());

    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let filename = file.display().to_string();

    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            diagnostics::render_parse_error(&source, &filename, &e);
            return 1;
        }
    };

    // Resolve and compile imported modules.
    let base_dir = file.parent().unwrap_or_else(|| std::path::Path::new("."));
    let mut imported_modules: Vec<kodo_ast::Module> = Vec::new();
    let mut import_visited: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();

    for import in &module.imports {
        let import_path = resolve_import_path(base_dir, &import.path);
        if !import_visited.insert(import_path.clone()) {
            continue;
        }
        let mut dummy_objects = Vec::new();
        match compile_imported_module(&import_path, &mut dummy_objects) {
            Ok(imported_module) => imported_modules.push(imported_module),
            Err(msg) => {
                eprintln!("{msg}");
                return 1;
            }
        }
    }

    // Load stdlib prelude for type checking.
    let mut checker = kodo_types::TypeChecker::new();
    for (_name, prelude_source) in kodo_std::prelude_sources() {
        if let Ok(prelude_mod) = kodo_parser::parse(prelude_source) {
            let _ = checker.check_module(&prelude_mod);
        }
    }

    // Type-check imported modules, then the user module.
    for imported in &imported_modules {
        if let Err(e) = checker.check_module(imported) {
            eprintln!("type error in imported module `{}`: {e}", imported.name);
            return 1;
        }
    }

    let type_errors = checker.check_module_collecting(&module);
    if !type_errors.is_empty() {
        for e in &type_errors {
            diagnostics::render_type_error(&source, &filename, e);
        }
        return 1;
    }

    // Contract verification.
    let contract_mode = parse_contract_mode(contracts_mode_str);
    for func in &module.functions {
        let contracts = kodo_contracts::extract_contracts(func);
        if let Err(e) = kodo_contracts::verify_contracts(&contracts, contract_mode) {
            eprintln!("contract error: {e}");
            return 1;
        }
    }
    for impl_block in &module.impl_blocks {
        for method in &impl_block.methods {
            let contracts = kodo_contracts::extract_contracts(method);
            if let Err(e) = kodo_contracts::verify_contracts(&contracts, contract_mode) {
                eprintln!("contract error: {e}");
                return 1;
            }
        }
    }

    // Desugar pass.
    let mut module = module;
    kodo_desugar::desugar_module(&mut module);

    // Lift impl block methods to top-level functions with mangled names.
    for impl_block in &module.impl_blocks {
        for method in &impl_block.methods {
            let mut func = method.clone();
            func.name = format!("{}_{}", impl_block.type_name, method.name);
            for param in &mut func.params {
                if param.name == "self" {
                    param.ty = kodo_ast::TypeExpr::Named(impl_block.type_name.clone());
                }
            }
            module.functions.push(func);
        }
    }

    // MIR lowering.
    let mir_functions = match kodo_mir::lowering::lower_module_with_type_info(
        &module,
        checker.struct_registry(),
        checker.enum_registry(),
        checker.enum_names(),
        checker.type_alias_registry(),
    ) {
        Ok(fns) => fns,
        Err(e) => {
            eprintln!("MIR lowering error: {e}");
            return 1;
        }
    };

    // Run MIR optimization passes.
    let mut mir_functions = mir_functions;
    kodo_mir::optimize::optimize_all(&mut mir_functions);

    // Print MIR to stdout.
    println!("--- MIR ({} functions) ---", mir_functions.len());
    for func in &mir_functions {
        println!("{func:#?}");
        println!();
    }
    println!("--- end MIR ---");

    0
}

fn run_check(file: &PathBuf, json_errors: bool, contracts_mode_str: &str) -> i32 {
    tracing::info!("checking {}", file.display());

    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let filename = file.display().to_string();

    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            if json_errors {
                diagnostics::render_parse_error_json(&source, &filename, &e);
            } else {
                diagnostics::render_parse_error(&source, &filename, &e);
            }
            return 1;
        }
    };

    // Resolve and compile imported modules.
    let base_dir = file.parent().unwrap_or_else(|| std::path::Path::new("."));
    let mut imported_modules: Vec<kodo_ast::Module> = Vec::new();
    let mut import_visited: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();

    for import in &module.imports {
        let import_path = resolve_import_path(base_dir, &import.path);
        if !import_visited.insert(import_path.clone()) {
            continue; // Skip duplicate imports.
        }
        let mut dummy_objects = Vec::new();
        match compile_imported_module(&import_path, &mut dummy_objects) {
            Ok(imported_module) => imported_modules.push(imported_module),
            Err(msg) => {
                eprintln!("{msg}");
                return 1;
            }
        }
    }

    // Load stdlib prelude for type checking.
    let mut checker = kodo_types::TypeChecker::new();
    for (_name, prelude_source) in kodo_std::prelude_sources() {
        if let Ok(prelude_mod) = kodo_parser::parse(prelude_source) {
            let _ = checker.check_module(&prelude_mod);
        }
    }

    // Type-check imported modules first, then the user module.
    for imported in &imported_modules {
        if let Err(e) = checker.check_module(imported) {
            eprintln!("type error in imported module `{}`: {e}", imported.name);
            return 1;
        }
    }

    // Type check — collect all errors for multi-error reporting.
    let type_errors = checker.check_module_collecting(&module);
    if !type_errors.is_empty() {
        for e in &type_errors {
            if json_errors {
                diagnostics::render_type_error_json(&source, &filename, e);
            } else {
                diagnostics::render_type_error(&source, &filename, e);
            }
        }
        return 1;
    }

    // Desugar pass — simplify syntactic sugar for consistency.
    let mut module = module;
    kodo_desugar::desugar_module(&mut module);

    // Contract verification
    let contract_mode = parse_contract_mode(contracts_mode_str);
    let mut total_static = 0_usize;
    let mut total_runtime = 0_usize;
    for func in &module.functions {
        let contracts = kodo_contracts::extract_contracts(func);
        match kodo_contracts::verify_contracts(&contracts, contract_mode) {
            Ok(result) => {
                if !result.failures.is_empty() {
                    for failure in &result.failures {
                        eprintln!("contract error: {failure}");
                    }
                    return 1;
                }
                total_static += result.static_verified;
                total_runtime += result.runtime_checks_needed;
            }
            Err(e) => {
                eprintln!("contract error: {e}");
                return 1;
            }
        }
    }
    for impl_block in &module.impl_blocks {
        for method in &impl_block.methods {
            let contracts = kodo_contracts::extract_contracts(method);
            match kodo_contracts::verify_contracts(&contracts, contract_mode) {
                Ok(result) => {
                    if !result.failures.is_empty() {
                        for failure in &result.failures {
                            eprintln!("contract error: {failure}");
                        }
                        return 1;
                    }
                    total_static += result.static_verified;
                    total_runtime += result.runtime_checks_needed;
                }
                Err(e) => {
                    eprintln!("contract error: {e}");
                    return 1;
                }
            }
        }
    }

    if json_errors {
        diagnostics::render_success_json(&module);
    } else {
        println!("Check passed for module `{}`", module.name);
        if total_static > 0 || total_runtime > 0 {
            println!(
                "  contracts: {} statically verified, {} runtime checks",
                total_static, total_runtime
            );
        }
    }
    0
}

fn run_lex(file: &PathBuf) -> i32 {
    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    match kodo_lexer::tokenize(&source) {
        Ok(tokens) => {
            for token in &tokens {
                println!(
                    "{:?} @ {}..{}",
                    token.kind, token.span.start, token.span.end
                );
            }
            println!("\n{} token(s)", tokens.len());
            0
        }
        Err(e) => {
            eprintln!("error: {e}");
            1
        }
    }
}

fn run_parse(file: &PathBuf) -> i32 {
    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    match kodo_parser::parse(&source) {
        Ok(module) => {
            println!("{module:#?}");
            0
        }
        Err(e) => {
            eprintln!("error: {e}");
            1
        }
    }
}

fn run_explain(code: &str) -> i32 {
    match explanations::get_explanation(code) {
        Some(entry) => {
            println!("Error {}: {}\n", entry.code, entry.title);
            println!("{}\n", entry.explanation);
            println!("Example of incorrect code:\n");
            println!("```kodo");
            println!("{}", entry.bad_example);
            println!("```\n");
            println!("Corrected code:\n");
            println!("```kodo");
            println!("{}", entry.good_example);
            println!("```");
            0
        }
        None => {
            eprintln!("error: unknown error code `{code}`");
            eprintln!("hint: error codes range from E0001 to E0699");
            1
        }
    }
}

fn run_fmt(file: &PathBuf, check: bool) -> i32 {
    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("error: {e}");
            return 1;
        }
    };

    let formatted = formatter::format_module(&module);

    if check {
        if formatted == source {
            0
        } else {
            eprintln!("Would reformat {}", file.display());
            1
        }
    } else if formatted == source {
        0
    } else {
        if let Err(e) = std::fs::write(file, &formatted) {
            eprintln!("error: could not write file `{}`: {e}", file.display());
            return 1;
        }
        println!("Formatted {}", file.display());
        0
    }
}

fn run_intent_explain(file: &PathBuf) -> i32 {
    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("error: {e}");
            return 1;
        }
    };

    if module.intent_decls.is_empty() {
        println!("No intents found in module `{}`", module.name);
        return 0;
    }

    let resolver = kodo_resolver::Resolver::with_builtins();
    for intent in &module.intent_decls {
        println!("Intent: `{}`", intent.name);
        println!("{}", "-".repeat(40));
        match resolver.resolve(intent) {
            Ok(resolved) => {
                println!("{}", kodo_resolver::format_resolved_intent(&resolved));
            }
            Err(e) => {
                eprintln!("  Error: {e}");
            }
        }
    }
    0
}

/// Generates a confidence report for a source file.
///
/// Parses the file, type-checks it (with the stdlib prelude), and then
/// asks the type checker to compute per-function confidence scores.
/// Reports both the declared `@confidence` value and the propagated
/// minimum across all direct callees.
fn run_confidence_report(file: &PathBuf, json: bool, threshold: f64) -> i32 {
    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("parse error: {e}");
            return 1;
        }
    };

    // Load stdlib prelude for type checking.
    let mut checker = kodo_types::TypeChecker::new();
    for (_name, prelude_source) in kodo_std::prelude_sources() {
        if let Ok(prelude_mod) = kodo_parser::parse(prelude_source) {
            let _ = checker.check_module(&prelude_mod);
        }
    }

    if let Err(e) = checker.check_module(&module) {
        eprintln!("type error: {e}");
        return 1;
    }

    let report = checker.confidence_report(&module);

    // Build a set of functions missing @authored_by.
    let missing_authored_by: Vec<String> = module
        .functions
        .iter()
        .filter(|f| !f.annotations.iter().any(|a| a.name == "authored_by"))
        .map(|f| f.name.clone())
        .collect();

    // Compute per-module average confidence (single module in a file).
    let module_avg = if report.is_empty() {
        1.0
    } else {
        report
            .iter()
            .map(|(_, _, computed, _)| *computed)
            .sum::<f64>()
            / report.len() as f64
    };

    // Overall project confidence: min of all function confidences.
    let overall = report
        .iter()
        .map(|(_, _, computed, _)| *computed)
        .fold(1.0_f64, f64::min);

    // Functions below the configurable threshold.
    let below_threshold: Vec<(&str, f64)> = report
        .iter()
        .filter(|(_, _, computed, _)| *computed < threshold)
        .map(|(name, _, computed, _)| (name.as_str(), *computed))
        .collect();

    if json {
        let functions: Vec<serde_json::Value> = report
            .iter()
            .map(|(name, declared, computed, callees)| {
                let has_authored_by = !missing_authored_by.contains(name);
                serde_json::json!({
                    "name": name,
                    "declared_confidence": declared,
                    "computed_confidence": computed,
                    "callees": callees,
                    "has_authored_by": has_authored_by,
                })
            })
            .collect();
        let below_threshold_json: Vec<serde_json::Value> = below_threshold
            .iter()
            .map(|(name, computed)| {
                serde_json::json!({
                    "name": name,
                    "computed_confidence": computed,
                })
            })
            .collect();
        let output = serde_json::json!({
            "module": module.name,
            "module_average_confidence": module_avg,
            "overall_confidence": overall,
            "threshold": threshold,
            "functions": functions,
            "missing_authored_by": missing_authored_by,
            "below_threshold": below_threshold_json,
        });
        println!(
            "{}",
            serde_json::to_string_pretty(&output)
                .unwrap_or_else(|e| format!("{{\"error\": \"json serialization failed: {e}\"}}"))
        );
    } else {
        println!("Confidence Report for module `{}`", module.name);
        println!("{}", "=".repeat(60));
        println!("Overall confidence: {overall:.2}");
        println!("Module average:     {module_avg:.2}");
        println!("Threshold:          {threshold:.2}");
        println!();
        println!(
            "{:<30} {:>10} {:>10}  Flags",
            "Function", "Declared", "Computed"
        );
        println!("{}", "-".repeat(70));
        for (name, declared, computed, _) in &report {
            let mut flags = Vec::new();
            if missing_authored_by.contains(name) {
                flags.push("no @authored_by");
            }
            if *computed < threshold {
                flags.push("below threshold");
            }
            let flag_str = if flags.is_empty() {
                String::new()
            } else {
                flags.join(", ")
            };
            println!("{name:<30} {declared:>10.2} {computed:>10.2}  {flag_str}");
        }

        // Summary of flagged functions.
        if !missing_authored_by.is_empty() {
            println!();
            println!("Functions missing @authored_by:");
            for name in &missing_authored_by {
                println!("  - {name}");
            }
        }
        if !below_threshold.is_empty() {
            println!();
            println!("Functions below threshold ({threshold:.2}):");
            for (name, computed) in &below_threshold {
                println!("  - {name} ({computed:.2})");
            }
        }
    }

    0
}

/// Attempts to auto-fix compiler errors in a source file.
///
/// Runs the parse and type-check pipeline, collects any [`kodo_ast::FixPatch`] diagnostics
/// produced, then either applies them in-place (default) or prints them as JSON
/// (`--dry-run`).
fn run_fix(file: &PathBuf, dry_run: bool) -> i32 {
    let source = match std::fs::read_to_string(file) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("error: could not read file `{}`: {e}", file.display());
            return 1;
        }
    };

    let filename = file.display().to_string();

    // Collect diagnostics by attempting to parse and type-check.
    let mut patches: Vec<kodo_ast::FixPatch> = Vec::new();

    // Try parsing first.
    let module = match kodo_parser::parse(&source) {
        Ok(m) => m,
        Err(e) => {
            use kodo_ast::Diagnostic;
            if let Some(patch) = e.fix_patch() {
                patches.push(patch);
            }
            if patches.is_empty() {
                eprintln!("parse error with no auto-fix available: {e}");
                return 1;
            }
            // Apply or show patches.
            return apply_patches(file, &source, &patches, dry_run);
        }
    };

    // Try type checking.
    let mut checker = kodo_types::TypeChecker::new();
    for (_name, prelude_source) in kodo_std::prelude_sources() {
        if let Ok(prelude_mod) = kodo_parser::parse(prelude_source) {
            let _ = checker.check_module(&prelude_mod);
        }
    }

    if let Err(e) = checker.check_module(&module) {
        use kodo_ast::Diagnostic;
        if let Some(mut patch) = e.fix_patch() {
            if patch.file.is_empty() {
                patch.file = filename;
            }
            patches.push(patch);
        }
    }

    if patches.is_empty() {
        println!("No auto-fixable errors found in `{}`", file.display());
        return 0;
    }

    apply_patches(file, &source, &patches, dry_run)
}

/// Applies or displays fix patches.
///
/// In dry-run mode, prints the patches as JSON without modifying any file.
/// Otherwise, applies the patches in reverse offset order (to preserve byte
/// offsets) and writes the result back to `file`.
fn apply_patches(
    file: &PathBuf,
    source: &str,
    patches: &[kodo_ast::FixPatch],
    dry_run: bool,
) -> i32 {
    if dry_run {
        let json_patches: Vec<serde_json::Value> = patches
            .iter()
            .map(|p| {
                serde_json::json!({
                    "description": p.description,
                    "file": p.file,
                    "start_offset": p.start_offset,
                    "end_offset": p.end_offset,
                    "replacement": p.replacement,
                })
            })
            .collect();
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({
                "patches": json_patches,
                "applied": false,
            }))
            .unwrap_or_else(|e| format!("{{\"error\": \"{e}\"}}"))
        );
        return 0;
    }

    // Apply patches in reverse order (by start_offset) to preserve offsets.
    let mut result = source.to_string();
    let mut sorted_patches: Vec<&kodo_ast::FixPatch> = patches.iter().collect();
    sorted_patches.sort_by(|a, b| b.start_offset.cmp(&a.start_offset));

    for patch in &sorted_patches {
        let start = patch.start_offset.min(result.len());
        let end = patch.end_offset.min(result.len());
        result.replace_range(start..end, &patch.replacement);
        println!("Applied fix: {}", patch.description);
    }

    if let Err(e) = std::fs::write(file, &result) {
        eprintln!("error: could not write file `{}`: {e}", file.display());
        return 1;
    }

    println!("Applied {} fix(es) to `{}`", patches.len(), file.display());
    0
}

/// Starts the Kōdo LSP server.
fn run_lsp() -> i32 {
    let rt = tokio::runtime::Runtime::new();
    match rt {
        Ok(rt) => {
            rt.block_on(async {
                if let Err(e) = kodo_lsp::run_server().await {
                    eprintln!("LSP server error: {e}");
                }
            });
            0
        }
        Err(e) => {
            eprintln!("Failed to start async runtime: {e}");
            1
        }
    }
}
