//! # kodoc -- The Kodo Compiler
//!
//! The command-line interface for the Kodo programming language compiler.
//! Designed to be used both by AI agents (with `--emit json-errors`) and
//! humans (with beautiful terminal error messages via ariadne).

mod annotate;
mod audit;
mod certificate;
mod commands;
mod dep_resolver;
mod diagnostics;
mod embedded_runtime;
mod explanations;
mod formatter;
mod lockfile;
mod manifest;
mod repl;
mod sarif;

use clap::{Parser, Subcommand};
use std::path::PathBuf;

/// The Kodo compiler -- a language built for AI agents, transparent for humans.
#[derive(Parser)]
#[command(name = "kodoc", version, about, long_about = None)]
struct Cli {
    /// Subcommand to execute.
    #[command(subcommand)]
    command: Command,
}

/// Available compiler commands.
#[derive(Subcommand)]
enum Command {
    /// Compile a Kodo source file to a binary.
    Build {
        /// The source file to compile.
        #[arg()]
        file: PathBuf,

        /// Output file path.
        #[arg(short, long)]
        output: Option<PathBuf>,

        /// Emit errors as JSON (for AI agent consumption). Alias for `--diagnostics-format=json`.
        #[arg(long, default_value_t = false)]
        json_errors: bool,

        /// Diagnostics output format: text (default), json, or sarif.
        #[arg(long)]
        diagnostics_format: Option<String>,

        /// Contract checking mode: static, runtime, both, none, recoverable.
        #[arg(long, default_value = "runtime")]
        contracts: String,

        /// Print the MIR (Mid-level IR) to stdout before code generation.
        #[arg(long, default_value_t = false)]
        emit_mir: bool,

        /// Number of green thread worker threads (0 = auto-detect via num_cpus).
        #[arg(long, default_value_t = 0)]
        threads: u32,

        /// Disable green thread yield point insertion and use legacy scheduler.
        #[arg(long, default_value_t = false)]
        no_green_threads: bool,

        /// Code generation backend: cranelift (default) or llvm.
        #[arg(long, default_value = "cranelift")]
        backend: String,

        /// Emit LLVM IR (.ll) file without compiling to native code (LLVM backend only).
        #[arg(long, default_value_t = false)]
        emit_llvm: bool,

        /// Build in release mode (alias for --backend=llvm).
        #[arg(long, default_value_t = false)]
        release: bool,
    },
    /// Lower a source file to MIR and print it without generating code.
    Mir {
        /// The source file to lower.
        #[arg()]
        file: PathBuf,

        /// Contract checking mode: static, runtime, both, none, recoverable.
        #[arg(long, default_value = "runtime")]
        contracts: String,
    },
    /// Type-check and verify contracts without generating code.
    Check {
        /// The source file to check.
        #[arg()]
        file: PathBuf,

        /// Emit errors as JSON. Alias for `--diagnostics-format=json`.
        #[arg(long, default_value_t = false)]
        json_errors: bool,

        /// Diagnostics output format: text (default), json, or sarif.
        #[arg(long)]
        diagnostics_format: Option<String>,

        /// Contract checking mode: static, runtime, both, none, recoverable.
        #[arg(long, default_value = "runtime")]
        contracts: String,

        /// Emit a compilation certificate (`<file>.cert.json`) after a successful check.
        #[arg(long, default_value_t = false)]
        emit_cert: bool,

        /// Emit repair plans as JSON for each error (for AI agent consumption).
        #[arg(long, default_value_t = false)]
        repair_plan: bool,
    },
    /// Tokenize a source file and print the token stream.
    Lex {
        /// The source file to tokenize.
        #[arg()]
        file: PathBuf,
    },
    /// Parse a source file and print the AST.
    Parse {
        /// The source file to parse.
        #[arg()]
        file: PathBuf,
    },
    /// Explain an error code in detail with examples.
    Explain {
        /// The error code to explain (e.g., E0200).
        #[arg()]
        code: String,

        /// Output as JSON instead of human-readable format.
        #[arg(long, default_value_t = false)]
        json: bool,
    },
    /// Format a Kodo source file.
    Fmt {
        /// The source file to format.
        #[arg()]
        file: PathBuf,

        /// Check formatting without modifying the file.
        #[arg(long, default_value_t = false)]
        check: bool,
    },
    /// Show the code generated by intent resolution.
    IntentExplain {
        /// The source file containing intents.
        #[arg()]
        file: PathBuf,

        /// Output as JSON instead of human-readable format.
        #[arg(long, default_value_t = false)]
        json: bool,
    },
    /// Start the Kodo Language Server Protocol server.
    Lsp,
    /// Start an interactive REPL (Read-Eval-Print Loop).
    Repl {
        /// Output all results as JSON (for AI agent consumption).
        #[arg(long, default_value_t = false)]
        json: bool,
    },
    /// Generate a confidence report for a module.
    ConfidenceReport {
        /// The source file to analyze.
        #[arg()]
        file: PathBuf,

        /// Output as JSON instead of human-readable table.
        #[arg(long, default_value_t = false)]
        json: bool,

        /// Confidence threshold -- functions below this value are flagged (0.0-1.0).
        #[arg(long, default_value_t = 0.8)]
        threshold: f64,
    },
    /// Apply auto-fix patches to resolve compiler errors.
    Fix {
        /// The source file to fix.
        #[arg()]
        file: PathBuf,

        /// Show patches without applying them.
        #[arg(long, default_value_t = false)]
        dry_run: bool,
    },
    /// Inspect metadata embedded in a compiled Kodo binary.
    Describe {
        /// The compiled binary to inspect.
        #[arg()]
        binary: PathBuf,

        /// Output as raw JSON instead of human-readable format.
        #[arg(long, default_value_t = false)]
        json: bool,
    },
    /// Run tests in a Kodo source file.
    Test {
        /// The source file containing tests.
        #[arg()]
        file: PathBuf,

        /// Filter tests by name substring.
        #[arg(long)]
        filter: Option<String>,

        /// Output results as JSON for agent consumption.
        #[arg(long, default_value_t = false)]
        json: bool,

        /// Contract checking mode: static, runtime, both, none, recoverable.
        #[arg(long, default_value = "runtime")]
        contracts: String,
    },
    /// Generate test stubs from function contracts in a Kodo source file.
    GenerateTests {
        /// The source file to analyze.
        #[arg()]
        file: PathBuf,

        /// Append generated tests inline into the source file.
        #[arg(long, default_value_t = false)]
        inline: bool,

        /// Print generated tests to stdout instead of writing a file.
        #[arg(long, default_value_t = false)]
        stdout: bool,

        /// Output as JSON (includes test count and generated source).
        #[arg(long, default_value_t = false)]
        json: bool,
    },
    /// Initialize a new Kodo project with kodo.toml and src/main.ko.
    Init {
        /// Project name (creates a new directory). If omitted, initializes the current directory.
        #[arg()]
        name: Option<String>,
    },
    /// Add a dependency to the current project.
    Add {
        /// Git repository URL or local path.
        #[arg()]
        source: String,

        /// Git tag to checkout (required for git deps).
        #[arg(long)]
        tag: Option<String>,

        /// Override the dependency name (derived from URL/path by default).
        #[arg(long)]
        name: Option<String>,

        /// Add as a path dependency instead of a git dependency.
        #[arg(long, default_value_t = false)]
        path: bool,
    },
    /// Remove a dependency from the current project.
    Remove {
        /// The name of the dependency to remove.
        #[arg()]
        name: String,
    },
    /// Re-resolve dependencies and update kodo.lock.
    Update {
        /// Specific dependency to update. If omitted, updates all.
        #[arg()]
        name: Option<String>,
    },
    /// Suggest missing contracts for functions using heuristic analysis.
    Annotate {
        /// The source file to analyze.
        #[arg()]
        file: PathBuf,

        /// Apply suggested contracts to the source file.
        #[arg(long, default_value_t = false)]
        apply: bool,

        /// Output as JSON (for AI agent consumption).
        #[arg(long, default_value_t = false)]
        json: bool,
    },
    /// Generate a consolidated audit report (confidence + contracts + annotations).
    Audit {
        /// The source file to audit.
        #[arg()]
        file: PathBuf,

        /// Output as JSON (default is human-readable).
        #[arg(long, default_value_t = false)]
        json: bool,

        /// Contract checking mode: static, runtime, both, none, recoverable.
        #[arg(long, default_value = "runtime")]
        contracts: String,

        /// Policy string for CI/CD gates (exit 1 on violation).
        ///
        /// Comma-separated key=value criteria. Supported keys:
        /// - `min_confidence=<float>` -- minimum effective confidence for all functions
        /// - `contracts=all_verified` -- all contracts must be statically verified
        /// - `contracts=all_present` -- all functions must have at least one contract
        /// - `reviewed=all` -- all functions must have `@reviewed_by` annotation
        #[arg(long)]
        policy: Option<String>,
    },
}

/// Resolves the effective diagnostics format from CLI flags.
///
/// `--diagnostics-format` takes priority over `--json-errors`.
/// When neither is specified, defaults to `Text`.
fn resolve_diagnostics_format(
    json_errors: bool,
    diagnostics_format: Option<&str>,
) -> diagnostics::DiagnosticsFormat {
    if let Some(fmt) = diagnostics_format {
        match fmt.to_lowercase().as_str() {
            "json" => diagnostics::DiagnosticsFormat::Json,
            "sarif" => diagnostics::DiagnosticsFormat::Sarif,
            "text" => diagnostics::DiagnosticsFormat::Text,
            other => {
                eprintln!("warning: unknown diagnostics format `{other}`, falling back to text");
                diagnostics::DiagnosticsFormat::Text
            }
        }
    } else if json_errors {
        diagnostics::DiagnosticsFormat::Json
    } else {
        diagnostics::DiagnosticsFormat::Text
    }
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("warn")),
        )
        .init();

    let cli = Cli::parse();

    let exit_code = match cli.command {
        Command::Build {
            file,
            output,
            json_errors,
            diagnostics_format,
            contracts,
            emit_mir,
            threads,
            no_green_threads,
            backend,
            emit_llvm,
            release,
        } => {
            // Set KODO_THREADS so the runtime picks up the requested thread count.
            if threads > 0 {
                std::env::set_var("KODO_THREADS", threads.to_string());
            }
            // --release is an alias for --backend=llvm.
            let effective_backend = if release { "llvm" } else { &backend };
            let diag_fmt = resolve_diagnostics_format(json_errors, diagnostics_format.as_deref());
            commands::build::run_build(
                &file,
                output.as_deref(),
                diag_fmt,
                &contracts,
                emit_mir,
                !no_green_threads,
                effective_backend,
                emit_llvm,
                release,
            )
        }
        Command::Mir { file, contracts } => commands::misc::run_mir(&file, &contracts),
        Command::Check {
            file,
            json_errors,
            diagnostics_format,
            contracts,
            emit_cert,
            repair_plan,
        } => {
            let diag_fmt = resolve_diagnostics_format(json_errors, diagnostics_format.as_deref());
            commands::check::run_check(&file, diag_fmt, &contracts, emit_cert, repair_plan)
        }
        Command::Lex { file } => commands::misc::run_lex(&file),
        Command::Parse { file } => commands::misc::run_parse(&file),
        Command::Explain { code, json } => commands::misc::run_explain(&code, json),
        Command::Fmt { file, check } => commands::misc::run_fmt(&file, check),
        Command::IntentExplain { file, json } => commands::misc::run_intent_explain(&file, json),
        Command::Lsp => commands::misc::run_lsp(),
        Command::Repl { json } => {
            if json {
                repl::run_repl_json()
            } else {
                repl::run_repl()
            }
        }
        Command::ConfidenceReport {
            file,
            json,
            threshold,
        } => commands::misc::run_confidence_report(&file, json, threshold),
        Command::Fix { file, dry_run } => commands::check::run_fix(&file, dry_run),
        Command::Test {
            file,
            filter,
            json,
            contracts,
        } => commands::test::run_test(&file, filter.as_deref(), json, &contracts),
        Command::Describe { binary, json } => commands::misc::run_describe(&binary, json),
        Command::GenerateTests {
            file,
            inline,
            stdout,
            json,
        } => commands::generate_tests::run_generate_tests(&file, inline, stdout, json),
        Command::Init { name } => commands::init::run_init(name.as_deref()),
        Command::Add {
            source,
            tag,
            name,
            path,
        } => {
            if path {
                commands::deps::run_add_path(&source, name.as_deref())
            } else {
                let tag = tag.unwrap_or_else(|| {
                    eprintln!("error: --tag is required for git dependencies");
                    std::process::exit(1);
                });
                commands::deps::run_add(&source, &tag, name.as_deref())
            }
        }
        Command::Remove { name } => commands::deps::run_remove(&name),
        Command::Update { name } => commands::deps::run_update(name.as_deref()),
        Command::Annotate { file, apply, json } => {
            let source = match std::fs::read_to_string(&file) {
                Ok(s) => s,
                Err(e) => {
                    eprintln!("error: could not read {}: {e}", file.display());
                    std::process::exit(1);
                }
            };
            let module = match kodo_parser::parse(&source) {
                Ok(m) => m,
                Err(e) => {
                    eprintln!("error: parse failed: {e:?}");
                    std::process::exit(1);
                }
            };
            let result = annotate::annotate_module(&module, &source);
            if json {
                match serde_json::to_string_pretty(&result) {
                    Ok(j) => println!("{j}"),
                    Err(e) => {
                        eprintln!("error: JSON serialization failed: {e}");
                        std::process::exit(1);
                    }
                }
            } else {
                print!(
                    "{}",
                    annotate::format_human(&result, &file.display().to_string())
                );
            }
            if apply && !result.suggestions.is_empty() {
                eprintln!(
                    "note: --apply is not yet implemented. Use the suggestions above to manually add contracts."
                );
            }
            0
        }
        Command::Audit {
            file,
            json,
            contracts,
            policy,
        } => commands::misc::run_audit(&file, json, &contracts, policy.as_deref()),
    };

    std::process::exit(exit_code);
}
