//! # `kodo_codegen_llvm` — LLVM IR Code Generation Backend for the Kodo Compiler
//!
//! This crate translates [`kodo_mir`] into textual LLVM IR (`.ll` files) that
//! can be compiled by `llc` into native object files. Unlike the Cranelift
//! backend (`kodo_codegen`), this backend has zero LLVM library dependencies —
//! it generates LLVM IR as plain text strings.
//!
//! ## Architecture
//!
//! The crate is split into the following internal modules:
//!
//! - `emitter` — Line-oriented LLVM IR string builder
//! - `types` — Kodo `Type` to LLVM type string mapping
//! - `function` — Per-function translation
//! - `instruction` — MIR instruction translation
//! - `terminator` — MIR terminator translation
//! - `value` — MIR value translation
//! - `builtins` — Runtime function `declare` statements
//!
//! ## Usage
//!
//! ```ignore
//! let ir = kodo_codegen_llvm::compile_module_to_llvm_ir(
//!     &mir_functions,
//!     &struct_defs,
//!     &enum_defs,
//!     &vtable_defs,
//!     &LLVMCodegenOptions::default(),
//! )?;
//! std::fs::write("output.ll", &ir)?;
//! ```
//!
//! ## Academic References
//!
//! - **\[Tiger\]** *Modern Compiler Implementation in ML* Ch. 9–11 — Instruction
//!   selection and code emission strategies.
//! - **\[EC\]** *Engineering a Compiler* Ch. 11–13 — Target-independent IR
//!   generation and lowering to machine-specific representations.
//!
//! See `docs/REFERENCES.md` for the full bibliography.

#![deny(missing_docs)]
#![deny(clippy::unwrap_used, clippy::expect_used)]
#![warn(clippy::pedantic)]

mod builtins;
mod emitter;
mod function;
mod instruction;
mod terminator;
mod types;
mod value;

use std::collections::HashMap;

use kodo_mir::MirFunction;
use kodo_types::Type;
use thiserror::Error;

/// Errors from LLVM IR code generation.
#[derive(Debug, Error)]
pub enum CodegenError {
    /// An unsupported MIR construct was encountered during translation.
    #[error("unsupported MIR construct: {0}")]
    Unsupported(String),
    /// An I/O error occurred while writing the `.ll` file.
    #[error("I/O error: {0}")]
    Io(String),
    /// The target triple is not recognized.
    #[error("unsupported target triple: {0}")]
    UnsupportedTarget(String),
}

/// Alias for results in this crate.
pub type Result<T> = std::result::Result<T, CodegenError>;

/// Options for LLVM IR code generation.
#[derive(Debug, Clone)]
pub struct LLVMCodegenOptions {
    /// The target triple (e.g., `"aarch64-apple-darwin"`).
    pub target_triple: String,
    /// Optimization level (0-3). Currently informational; `llc` handles optimization.
    pub opt_level: u8,
}

impl Default for LLVMCodegenOptions {
    fn default() -> Self {
        Self {
            target_triple: detect_target_triple(),
            opt_level: 0,
        }
    }
}

/// A vtable entry mapping `(concrete_type, trait_name)` to method function names.
///
/// Re-exported for API symmetry with `kodo_codegen`.
pub type VtableDef = Vec<String>;

/// Compiles MIR functions into a complete LLVM IR `.ll` file as a `String`.
///
/// The returned string is valid LLVM IR that can be passed to `llc` for
/// compilation to native object code.
///
/// # Arguments
/// * `mir_functions` - All MIR functions to compile.
/// * `struct_defs` - Struct type definitions (name -> fields).
/// * `enum_defs` - Enum type definitions (name -> variants).
/// * `vtable_defs` - Virtual dispatch table definitions.
/// * `options` - Code generation options (target triple, opt level).
///
/// # Errors
///
/// Returns [`CodegenError`] if translation fails.
#[allow(clippy::implicit_hasher)]
pub fn compile_module_to_llvm_ir(
    mir_functions: &[MirFunction],
    struct_defs: &HashMap<String, Vec<(String, Type)>>,
    enum_defs: &HashMap<String, Vec<(String, Vec<Type>)>>,
    _vtable_defs: &HashMap<(String, String), VtableDef>,
    options: &LLVMCodegenOptions,
) -> Result<String> {
    let mut emitter = emitter::LLVMEmitter::new();

    // -- Module header --
    emitter.comment("Generated by kodoc (kodo_codegen_llvm)");
    let datalayout = target_datalayout(&options.target_triple);
    emitter.line(&format!("target datalayout = \"{datalayout}\""));
    emitter.line(&format!("target triple = \"{}\"", options.target_triple));
    emitter.blank();

    // -- Struct type definitions --
    let struct_type_defs = types::emit_struct_type_defs(struct_defs, enum_defs);
    if !struct_type_defs.is_empty() {
        emitter.comment("Struct type definitions");
        for def in &struct_type_defs {
            emitter.line(def);
        }
        emitter.blank();
    }

    // -- Runtime declarations --
    emitter.comment("Runtime function declarations");
    let runtime_decls = builtins::emit_runtime_declarations();
    for decl in &runtime_decls {
        emitter.line(decl);
    }
    emitter.blank();

    // -- Collect user function names --
    let user_functions: Vec<String> = mir_functions
        .iter()
        .map(|f| {
            if f.name == "main" {
                "kodo_main".to_string()
            } else {
                f.name.clone()
            }
        })
        .collect();

    // -- Forward-declare user functions that are only declared, not defined --
    // Functions with bodies will be emitted as `define` later — emitting
    // both `declare` and `define` for the same name is an LLVM IR error.
    // Only emit `declare` for functions that are referenced but not defined
    // in this module (e.g., imported from other modules).
    // Since all MIR functions will be defined below, we skip forward declarations.
    emitter.blank();

    // -- Function definitions --
    let mut string_constants: Vec<(String, String)> = Vec::new();
    let mut function_irs: Vec<String> = Vec::new();

    for func in mir_functions {
        let ir = function::emit_function(
            func,
            struct_defs,
            enum_defs,
            &mut string_constants,
            &user_functions,
        );
        function_irs.push(ir);
    }

    // -- String constants (emitted before functions so they're available) --
    if !string_constants.is_empty() {
        emitter.comment("String constants");
        for (name, value) in &string_constants {
            let len = value.len();
            let escaped = escape_llvm_string(value);
            emitter.line(&format!(
                "@{name} = private unnamed_addr constant [{len} x i8] c\"{escaped}\""
            ));
        }
        emitter.blank();
    }

    // -- Emit function definitions --
    emitter.comment("Function definitions");
    for ir in &function_irs {
        emitter.line(ir);
        emitter.blank();
    }

    Ok(emitter.finish())
}

/// Detects the target triple for the current platform.
fn detect_target_triple() -> String {
    if cfg!(target_os = "macos") {
        if cfg!(target_arch = "aarch64") {
            "aarch64-apple-darwin".to_string()
        } else {
            "x86_64-apple-darwin".to_string()
        }
    } else if cfg!(target_os = "linux") {
        if cfg!(target_arch = "aarch64") {
            "aarch64-unknown-linux-gnu".to_string()
        } else {
            "x86_64-unknown-linux-gnu".to_string()
        }
    } else {
        "x86_64-unknown-unknown".to_string()
    }
}

/// Returns the LLVM data layout string for a target triple.
fn target_datalayout(triple: &str) -> &'static str {
    if triple.contains("aarch64") && triple.contains("apple") {
        "e-m:o-i64:64-i128:128-n32:64-S128"
    } else if triple.contains("x86_64") && triple.contains("apple") {
        "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
    } else if triple.contains("aarch64") && triple.contains("linux") {
        "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
    } else {
        // x86_64 linux default
        "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
    }
}

/// Escapes a string for LLVM IR constant representation.
fn escape_llvm_string(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for byte in s.bytes() {
        if byte == b'\\' {
            result.push_str("\\5C");
        } else if byte == b'"' {
            result.push_str("\\22");
        } else if byte == b'\n' {
            result.push_str("\\0A");
        } else if byte == b'\r' {
            result.push_str("\\0D");
        } else if byte == b'\t' {
            result.push_str("\\09");
        } else if byte == 0 {
            result.push_str("\\00");
        } else if byte.is_ascii_graphic() || byte == b' ' {
            result.push(byte as char);
        } else {
            use std::fmt::Write;
            let _ = write!(result, "\\{byte:02X}");
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use kodo_mir::{BasicBlock, BlockId, Instruction, Local, LocalId, Terminator, Value};

    #[test]
    fn compile_empty_main() {
        let func = MirFunction {
            name: "main".to_string(),
            return_type: Type::Unit,
            param_count: 0,
            locals: vec![],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![],
                terminator: Terminator::Return(Value::Unit),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("target triple"));
        assert!(ir.contains("@kodo_main"));
        assert!(ir.contains("ret void"));
    }

    #[test]
    fn compile_return_42() {
        let func = MirFunction {
            name: "answer".to_string(),
            return_type: Type::Int,
            param_count: 0,
            locals: vec![],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![],
                terminator: Terminator::Return(Value::IntConst(42)),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("define i64 @answer()"));
        assert!(ir.contains("ret i64 42"));
    }

    #[test]
    fn compile_with_string_constant() {
        let func = MirFunction {
            name: "greet".to_string(),
            return_type: Type::Unit,
            param_count: 0,
            locals: vec![Local {
                id: LocalId(0),
                ty: Type::Unit,
                mutable: false,
            }],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![Instruction::Call {
                    dest: LocalId(0),
                    callee: "println".to_string(),
                    args: vec![Value::StringConst("hello".to_string())],
                }],
                terminator: Terminator::Return(Value::Unit),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(
            ir.contains("hello"),
            "IR should contain string constant 'hello'"
        );
        assert!(ir.contains("kodo_println"), "IR should call kodo_println");
    }

    #[test]
    fn compile_with_struct_defs() {
        let struct_defs = HashMap::from([(
            "Point".to_string(),
            vec![("x".to_string(), Type::Int), ("y".to_string(), Type::Int)],
        )]);
        let func = MirFunction {
            name: "make".to_string(),
            return_type: Type::Struct("Point".to_string()),
            param_count: 0,
            locals: vec![Local {
                id: LocalId(0),
                ty: Type::Struct("Point".to_string()),
                mutable: false,
            }],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![Instruction::Assign(
                    LocalId(0),
                    Value::StructLit {
                        name: "Point".to_string(),
                        fields: vec![
                            ("x".to_string(), Value::IntConst(1)),
                            ("y".to_string(), Value::IntConst(2)),
                        ],
                    },
                )],
                terminator: Terminator::Return(Value::Local(LocalId(0))),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &struct_defs,
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("%Point = type { i64, i64 }"));
    }

    #[test]
    fn compile_with_branch() {
        let func = MirFunction {
            name: "branchy".to_string(),
            return_type: Type::Int,
            param_count: 0,
            locals: vec![],
            blocks: vec![
                BasicBlock {
                    id: BlockId(0),
                    instructions: vec![],
                    terminator: Terminator::Branch {
                        condition: Value::BoolConst(true),
                        true_block: BlockId(1),
                        false_block: BlockId(2),
                    },
                },
                BasicBlock {
                    id: BlockId(1),
                    instructions: vec![],
                    terminator: Terminator::Return(Value::IntConst(1)),
                },
                BasicBlock {
                    id: BlockId(2),
                    instructions: vec![],
                    terminator: Terminator::Return(Value::IntConst(0)),
                },
            ],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("br i1"));
        assert!(ir.contains("bb1:"));
        assert!(ir.contains("bb2:"));
    }

    #[test]
    fn compile_arithmetic() {
        let func = MirFunction {
            name: "arith".to_string(),
            return_type: Type::Int,
            param_count: 0,
            locals: vec![],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![],
                terminator: Terminator::Return(Value::BinOp(
                    kodo_ast::BinOp::Add,
                    Box::new(Value::IntConst(1)),
                    Box::new(Value::IntConst(2)),
                )),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("add i64"));
    }

    #[test]
    fn compile_float_arithmetic() {
        let func = MirFunction {
            name: "float_add".to_string(),
            return_type: Type::Float64,
            param_count: 0,
            locals: vec![],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![],
                terminator: Terminator::Return(Value::BinOp(
                    kodo_ast::BinOp::Add,
                    Box::new(Value::FloatConst(1.5)),
                    Box::new(Value::FloatConst(2.5)),
                )),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("fadd double"));
    }

    #[test]
    fn compile_multiple_functions() {
        let double = MirFunction {
            name: "double".to_string(),
            return_type: Type::Int,
            param_count: 1,
            locals: vec![Local {
                id: LocalId(0),
                ty: Type::Int,
                mutable: false,
            }],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![],
                terminator: Terminator::Return(Value::BinOp(
                    kodo_ast::BinOp::Mul,
                    Box::new(Value::Local(LocalId(0))),
                    Box::new(Value::IntConst(2)),
                )),
            }],
            entry: BlockId(0),
        };
        let main_fn = MirFunction {
            name: "main".to_string(),
            return_type: Type::Int,
            param_count: 0,
            locals: vec![Local {
                id: LocalId(0),
                ty: Type::Int,
                mutable: false,
            }],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![Instruction::Call {
                    dest: LocalId(0),
                    callee: "double".to_string(),
                    args: vec![Value::IntConst(21)],
                }],
                terminator: Terminator::Return(Value::Local(LocalId(0))),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[double, main_fn],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("@double"));
        assert!(ir.contains("@kodo_main"));
        assert!(ir.contains("call i64 @double"));
    }

    #[test]
    fn escape_special_chars() {
        assert_eq!(escape_llvm_string("hello"), "hello");
        assert_eq!(escape_llvm_string("a\"b"), "a\\22b");
        assert_eq!(escape_llvm_string("a\\b"), "a\\5Cb");
        assert_eq!(escape_llvm_string("a\nb"), "a\\0Ab");
    }

    #[test]
    fn default_options_have_triple() {
        let opts = LLVMCodegenOptions::default();
        assert!(!opts.target_triple.is_empty());
        assert_eq!(opts.opt_level, 0);
    }

    #[test]
    fn codegen_error_display() {
        let err = CodegenError::Unsupported("test".to_string());
        assert!(format!("{err}").contains("test"));

        let err = CodegenError::Io("disk full".to_string());
        assert!(format!("{err}").contains("disk full"));

        let err = CodegenError::UnsupportedTarget("mips".to_string());
        assert!(format!("{err}").contains("mips"));
    }

    #[test]
    fn runtime_declarations_included() {
        let func = MirFunction {
            name: "test".to_string(),
            return_type: Type::Unit,
            param_count: 0,
            locals: vec![],
            blocks: vec![BasicBlock {
                id: BlockId(0),
                instructions: vec![],
                terminator: Terminator::Return(Value::Unit),
            }],
            entry: BlockId(0),
        };
        let result = compile_module_to_llvm_ir(
            &[func],
            &HashMap::new(),
            &HashMap::new(),
            &HashMap::new(),
            &LLVMCodegenOptions::default(),
        );
        assert!(result.is_ok());
        let ir = result.ok().unwrap_or_default();
        assert!(ir.contains("declare void @kodo_println(i64, i64)"));
        assert!(ir.contains("declare i64 @kodo_list_new()"));
    }
}
