//! # `kodo_runtime` — Runtime Support for Compiled Kōdo Programs
//!
//! This crate is compiled as a static library (`libkodo_runtime.a`) and linked
//! into every Kōdo executable. It provides the entry point (`main` → `kodo_main`)
//! and native implementations of builtin functions like `println` and `print`.
//!
//! All exported functions use `extern "C"` linkage so the Cranelift-generated
//! code can call them directly.
//!
//! ## Modules
//!
//! - [`string_ops`] — String manipulation builtins
//! - [`math_ops`] — Numeric builtins (abs, min, max, clamp)
//! - [`io_ops`] — File I/O, time, environment, JSON
//! - [`collections`] — List and Map builtins, actor runtime
//! - [`scheduler`] — Cooperative scheduler, channels, async runtime
//! - [`memory`] — Reference-counted allocator
//! - [`http`] — HTTP client builtins
//! - `helpers` — Internal helper functions

#![deny(clippy::unwrap_used, clippy::expect_used)]
#![warn(clippy::pedantic)]

pub mod collections;
mod helpers;
pub mod http;
pub mod io_ops;
pub mod math_ops;
pub mod memory;
pub mod scheduler;
pub mod string_ops;

// Re-export all public #[no_mangle] functions so they remain visible
// in the final staticlib. Each module's public extern "C" functions
// are already #[no_mangle] and will be included in the link.

#[cfg(not(test))]
extern "C" {
    /// The Kōdo program's main function, generated by the compiler.
    fn kodo_main();
    /// First byte of embedded module metadata (JSON).
    static kodo_meta: u8;
    /// Length of the embedded metadata in bytes.
    static kodo_meta_len: u64;
}

/// Entry point for compiled Kōdo programs.
///
/// If invoked with `--describe`, prints the embedded module metadata JSON
/// and exits. Otherwise calls the compiler-generated `kodo_main`.
///
/// Only compiled when building the staticlib (not during `cargo test`).
///
/// # Safety
///
/// `argv` must point to `argc` valid C string pointers (provided by the OS).
#[cfg(not(test))]
#[no_mangle]
pub unsafe extern "C" fn main(arg_count: i32, arg_values: *const *const i8) -> i32 {
    if arg_count == 2 {
        // SAFETY: arg_values is provided by the OS and points to arg_count valid pointers.
        let arg = unsafe { std::ffi::CStr::from_ptr(*arg_values.add(1)) };
        if arg.to_bytes() == b"--describe" {
            // SAFETY: kodo_meta/kodo_meta_len are defined by the compiler
            // in the same binary.
            #[allow(clippy::cast_possible_truncation)]
            let len = unsafe { kodo_meta_len } as usize;
            let ptr = std::ptr::addr_of!(kodo_meta);
            // SAFETY: ptr/len describe a valid byte slice embedded by the compiler.
            let slice = unsafe { std::slice::from_raw_parts(ptr, len) };
            let _ = std::io::Write::write_all(&mut std::io::stdout(), slice);
            let _ = std::io::Write::write_all(&mut std::io::stdout(), b"\n");
            return 0;
        }
    }
    // SAFETY: kodo_main is generated by the Kōdo compiler and linked into
    // the same binary. It uses the C calling convention.
    unsafe {
        kodo_main();
    }
    // Run any spawned tasks.
    scheduler::kodo_run_scheduler();
    0
}
