//! # `kodo_runtime` — Runtime Support for Compiled Kōdo Programs
//!
//! This crate is compiled as a static library (`libkodo_runtime.a`) and linked
//! into every Kōdo executable. It provides the entry point (`main` → `kodo_main`)
//! and native implementations of builtin functions like `println` and `print`.
//!
//! All exported functions use `extern "C"` linkage so the Cranelift-generated
//! code can call them directly.

#![deny(clippy::unwrap_used, clippy::expect_used)]
#![warn(clippy::pedantic)]

use std::io::Write;

#[cfg(not(test))]
extern "C" {
    /// The Kōdo program's main function, generated by the compiler.
    fn kodo_main();
    /// First byte of embedded module metadata (JSON).
    static kodo_meta: u8;
    /// Length of the embedded metadata in bytes.
    static kodo_meta_len: u64;
}

/// Entry point for compiled Kōdo programs.
///
/// If invoked with `--describe`, prints the embedded module metadata JSON
/// and exits. Otherwise calls the compiler-generated `kodo_main`.
///
/// Only compiled when building the staticlib (not during `cargo test`).
///
/// # Safety
///
/// `argv` must point to `argc` valid C string pointers (provided by the OS).
#[cfg(not(test))]
#[no_mangle]
pub unsafe extern "C" fn main(arg_count: i32, arg_values: *const *const i8) -> i32 {
    if arg_count == 2 {
        // SAFETY: arg_values is provided by the OS and points to arg_count valid pointers.
        let arg = unsafe { std::ffi::CStr::from_ptr(*arg_values.add(1)) };
        if arg.to_bytes() == b"--describe" {
            // SAFETY: kodo_meta/kodo_meta_len are defined by the compiler
            // in the same binary.
            #[allow(clippy::cast_possible_truncation)]
            let len = unsafe { kodo_meta_len } as usize;
            let ptr = std::ptr::addr_of!(kodo_meta);
            let slice = unsafe { std::slice::from_raw_parts(ptr, len) };
            let _ = std::io::Write::write_all(&mut std::io::stdout(), slice);
            let _ = std::io::Write::write_all(&mut std::io::stdout(), b"\n");
            return 0;
        }
    }
    // SAFETY: kodo_main is generated by the Kōdo compiler and linked into
    // the same binary. It uses the C calling convention.
    unsafe {
        kodo_main();
    }
    // Run any spawned tasks.
    kodo_run_scheduler();
    0
}

/// Prints a string followed by a newline to stdout.
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
#[no_mangle]
pub unsafe extern "C" fn kodo_println(ptr: *const u8, len: usize) {
    // SAFETY: Caller guarantees ptr/len form a valid UTF-8 slice.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = handle.write_all(bytes);
    let _ = handle.write_all(b"\n");
    let _ = handle.flush();
}

/// Prints a string to stdout without a trailing newline.
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
#[no_mangle]
pub unsafe extern "C" fn kodo_print(ptr: *const u8, len: usize) {
    // SAFETY: Caller guarantees ptr/len form a valid UTF-8 slice.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = handle.write_all(bytes);
    let _ = handle.flush();
}

/// Prints an integer to stdout followed by a newline.
#[no_mangle]
pub extern "C" fn kodo_print_int(n: i64) {
    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = write!(handle, "{n}");
    let _ = handle.write_all(b"\n");
    let _ = handle.flush();
}

/// Prints a float to stdout without a newline.
#[no_mangle]
pub extern "C" fn kodo_print_float(value: f64) {
    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = write!(handle, "{value}");
    let _ = handle.flush();
}

/// Prints a float to stdout followed by a newline.
#[no_mangle]
pub extern "C" fn kodo_println_float(value: f64) {
    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    let _ = write!(handle, "{value}");
    let _ = handle.write_all(b"\n");
    let _ = handle.flush();
}

/// Called when a contract (`requires`/`ensures`) check fails at runtime.
///
/// Prints an error message to stderr and aborts the process.
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
#[no_mangle]
pub unsafe extern "C" fn kodo_contract_fail(ptr: *const u8, len: usize) {
    // SAFETY: Caller guarantees ptr/len form a valid UTF-8 slice.
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    let msg = std::str::from_utf8(bytes).unwrap_or("<invalid utf-8>");
    eprintln!("contract violation: {msg}");
    std::process::abort();
}

/// Returns the absolute value of an integer.
#[no_mangle]
pub extern "C" fn kodo_abs(n: i64) -> i64 {
    n.wrapping_abs()
}

/// Returns the minimum of two integers.
#[no_mangle]
pub extern "C" fn kodo_min(a: i64, b: i64) -> i64 {
    if a < b {
        a
    } else {
        b
    }
}

/// Returns the maximum of two integers.
#[no_mangle]
pub extern "C" fn kodo_max(a: i64, b: i64) -> i64 {
    if a > b {
        a
    } else {
        b
    }
}

/// Clamps a value between a minimum and maximum.
#[no_mangle]
pub extern "C" fn kodo_clamp(val: i64, lo: i64, hi: i64) -> i64 {
    if val < lo {
        lo
    } else if val > hi {
        hi
    } else {
        val
    }
}

/// Returns the length of a string (number of bytes).
///
/// # Safety
///
/// `ptr` must point to `len` valid bytes.
#[no_mangle]
pub extern "C" fn kodo_string_length(_ptr: *const u8, len: usize) -> i64 {
    #[allow(clippy::cast_possible_wrap)]
    let result = len as i64;
    result
}

/// Returns 1 if the haystack string contains the needle string, 0 otherwise.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_contains(
    hay_ptr: *const u8,
    hay_len: usize,
    needle_ptr: *const u8,
    needle_len: usize,
) -> i64 {
    let haystack = unsafe { std::slice::from_raw_parts(hay_ptr, hay_len) };
    let needle = unsafe { std::slice::from_raw_parts(needle_ptr, needle_len) };
    // Byte-level substring search — no UTF-8 decoding needed.
    i64::from(contains_bytes(haystack, needle))
}

/// Returns 1 if the string starts with the given prefix, 0 otherwise.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_starts_with(
    hay_ptr: *const u8,
    hay_len: usize,
    prefix_ptr: *const u8,
    prefix_len: usize,
) -> i64 {
    let haystack = unsafe { std::slice::from_raw_parts(hay_ptr, hay_len) };
    let prefix = unsafe { std::slice::from_raw_parts(prefix_ptr, prefix_len) };
    i64::from(haystack.starts_with(prefix))
}

/// Returns 1 if the string ends with the given suffix, 0 otherwise.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_ends_with(
    hay_ptr: *const u8,
    hay_len: usize,
    suffix_ptr: *const u8,
    suffix_len: usize,
) -> i64 {
    let haystack = unsafe { std::slice::from_raw_parts(hay_ptr, hay_len) };
    let suffix = unsafe { std::slice::from_raw_parts(suffix_ptr, suffix_len) };
    i64::from(haystack.ends_with(suffix))
}

/// Returns 1 if two strings are equal (same length and bytes), 0 otherwise.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_eq(
    ptr1: *const u8,
    len1: usize,
    ptr2: *const u8,
    len2: usize,
) -> i64 {
    if len1 != len2 {
        return 0;
    }
    let s1 = unsafe { std::slice::from_raw_parts(ptr1, len1) };
    let s2 = unsafe { std::slice::from_raw_parts(ptr2, len2) };
    i64::from(s1 == s2)
}

/// Concatenates two strings, writing the result via out-parameters.
///
/// The caller is responsible for eventually freeing the allocated memory.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_string_concat(
    ptr1: *const u8,
    len1: usize,
    ptr2: *const u8,
    len2: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let s1 = unsafe { std::slice::from_raw_parts(ptr1, len1) };
    let s2 = unsafe { std::slice::from_raw_parts(ptr2, len2) };
    let mut result = Vec::with_capacity(len1 + len2);
    result.extend_from_slice(s1);
    result.extend_from_slice(s2);
    let boxed = result.into_boxed_slice();
    let result_len = boxed.len();
    // SAFETY: Box::into_raw intentionally leaks the allocation so the caller
    // can manage the memory via (ptr, len). Freed by `kodo_string_free`.
    let result_ptr = Box::into_raw(boxed) as *const u8;
    unsafe {
        *out_ptr = result_ptr;
        *out_len = result_len;
    }
}

/// Returns the byte index of the first occurrence of needle in haystack, or -1 if not found.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_index_of(
    hay_ptr: *const u8,
    hay_len: usize,
    needle_ptr: *const u8,
    needle_len: usize,
) -> i64 {
    let haystack = unsafe { std::slice::from_raw_parts(hay_ptr, hay_len) };
    let needle = unsafe { std::slice::from_raw_parts(needle_ptr, needle_len) };
    if needle.is_empty() {
        return 0;
    }
    if needle_len > hay_len {
        return -1;
    }
    for i in 0..=(hay_len - needle_len) {
        if haystack[i..i + needle_len] == *needle {
            #[allow(clippy::cast_possible_wrap)]
            return i as i64;
        }
    }
    -1
}

/// Replaces all occurrences of a pattern in a string, writing the result via out-parameters.
///
/// The caller is responsible for eventually freeing the allocated memory.
///
/// # Safety
///
/// All pointer/length pairs must point to valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_replace(
    hay_ptr: *const u8,
    hay_len: usize,
    pattern_ptr: *const u8,
    pattern_len: usize,
    replacement_ptr: *const u8,
    replacement_len: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let haystack = unsafe { std::slice::from_raw_parts(hay_ptr, hay_len) };
    let pattern = unsafe { std::slice::from_raw_parts(pattern_ptr, pattern_len) };
    let replacement = unsafe { std::slice::from_raw_parts(replacement_ptr, replacement_len) };

    if pattern.is_empty() {
        // Empty pattern: return the original string (no replacement)
        let copy = haystack.to_vec().into_boxed_slice();
        let result_len = copy.len();
        // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
        let result_ptr = Box::into_raw(copy) as *const u8;
        unsafe {
            *out_ptr = result_ptr;
            *out_len = result_len;
        }
        return;
    }

    let mut result = Vec::with_capacity(hay_len);
    let mut i = 0;
    while i < hay_len {
        if i + pattern_len <= hay_len && haystack[i..i + pattern_len] == *pattern {
            result.extend_from_slice(replacement);
            i += pattern_len;
        } else {
            result.push(haystack[i]);
            i += 1;
        }
    }
    let boxed = result.into_boxed_slice();
    let result_len = boxed.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    let result_ptr = Box::into_raw(boxed) as *const u8;
    unsafe {
        *out_ptr = result_ptr;
        *out_len = result_len;
    }
}

/// Byte-level substring search.
fn contains_bytes(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() {
        return true;
    }
    haystack
        .windows(needle.len())
        .any(|window| window == needle)
}

/// Returns a trimmed copy of the string (whitespace removed from both ends).
///
/// The result pointer and length are written to `out_ptr` and `out_len`.
/// The trimmed string is a sub-slice of the original, so no allocation is needed.
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_string_trim(
    ptr: *const u8,
    len: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    // Find the trimmed sub-slice at the byte level.
    let start = bytes
        .iter()
        .position(|b| !b.is_ascii_whitespace())
        .unwrap_or(len);
    let end = bytes
        .iter()
        .rposition(|b| !b.is_ascii_whitespace())
        .map_or(start, |p| p + 1);
    unsafe {
        *out_ptr = bytes.as_ptr().add(start);
        *out_len = end - start;
    }
}

/// Returns an uppercase copy of the string.
///
/// Allocates a new string on the heap. Caller does not need to free
/// (managed by the Kōdo runtime's arena).
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_string_to_upper(
    ptr: *const u8,
    len: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    // ASCII-level uppercase conversion (safe for any byte sequence).
    let mut result = Vec::with_capacity(len);
    for &b in bytes {
        result.push(b.to_ascii_uppercase());
    }
    let boxed = result.into_boxed_slice();
    let result_len = boxed.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    let result_ptr = Box::into_raw(boxed) as *const u8;
    unsafe {
        *out_ptr = result_ptr;
        *out_len = result_len;
    }
}

/// Returns a lowercase copy of the string.
///
/// Allocates a new string on the heap.
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_string_to_lower(
    ptr: *const u8,
    len: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    // ASCII-level lowercase conversion (safe for any byte sequence).
    let mut result = Vec::with_capacity(len);
    for &b in bytes {
        result.push(b.to_ascii_lowercase());
    }
    let boxed = result.into_boxed_slice();
    let result_len = boxed.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    let result_ptr = Box::into_raw(boxed) as *const u8;
    unsafe {
        *out_ptr = result_ptr;
        *out_len = result_len;
    }
}

/// Returns a substring from `start` to `end` byte indices.
///
/// Clamps indices to valid range. The result is a sub-slice (no allocation).
///
/// # Safety
///
/// `ptr` must point to `len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_string_substring(
    ptr: *const u8,
    len: usize,
    start: i64,
    end: i64,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let start_idx = (start.max(0) as usize).min(len);
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let end_idx = (end.max(0) as usize).min(len);
    let actual_end = end_idx.max(start_idx);
    unsafe {
        *out_ptr = bytes.as_ptr().add(start_idx);
        *out_len = actual_end - start_idx;
    }
}

/// Converts an integer to its decimal string representation.
///
/// Allocates a new string on the heap.
///
/// # Safety
///
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_int_to_string(
    value: i64,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let s = value.to_string();
    let boxed = s.into_boxed_str();
    let result_len = boxed.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    let result_ptr = Box::into_raw(boxed) as *const u8;
    unsafe {
        *out_ptr = result_ptr;
        *out_len = result_len;
    }
}

/// Converts an integer to a 64-bit float.
#[no_mangle]
pub extern "C" fn kodo_int_to_float64(value: i64) -> f64 {
    #[allow(clippy::cast_precision_loss)]
    let result = value as f64;
    result
}

/// Converts a 64-bit float to its string representation.
///
/// # Safety
///
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_float64_to_string(
    value: f64,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) {
    let s = value.to_string();
    let boxed = s.into_boxed_str();
    let result_len = boxed.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    let result_ptr = Box::into_raw(boxed) as *const u8;
    unsafe {
        *out_ptr = result_ptr;
        *out_len = result_len;
    }
}

/// Converts a 64-bit float to an integer (truncates toward zero).
#[no_mangle]
pub extern "C" fn kodo_float64_to_int(value: f64) -> i64 {
    #[allow(clippy::cast_possible_truncation)]
    let result = value as i64;
    result
}

/// A queued task — either a plain function pointer or one with an environment.
enum Task {
    /// A zero-argument task (no captures).
    Plain(extern "C" fn()),
    /// A task with a captured environment.
    ///
    /// The function takes a pointer to the environment data. The `env` Vec
    /// owns the copied environment bytes so they stay alive until the task
    /// runs.
    WithEnv {
        /// Function pointer that accepts an env pointer as its sole argument.
        func: extern "C" fn(i64),
        /// Owned copy of the environment data.
        env: Vec<u8>,
    },
}

/// Task queue for the cooperative scheduler.
///
/// Stores tasks that have been spawned — either plain function pointers or
/// functions paired with captured environment data.
/// All tasks are executed when `kodo_run_scheduler` is called.
static TASK_QUEUE: std::sync::Mutex<Vec<Task>> = std::sync::Mutex::new(Vec::new());

/// A task inside a parallel group.
enum ParallelTask {
    /// A plain function with no captures.
    Plain(extern "C" fn()),
    /// A function that takes a captured-environment pointer.
    WithEnv {
        /// The function pointer.
        func: extern "C" fn(i64),
        /// Captured environment bytes (copied from caller stack).
        env: Vec<u8>,
    },
}

/// A group of tasks to be executed in parallel.
struct ParallelGroup {
    /// The tasks queued for parallel execution.
    tasks: Vec<ParallelTask>,
}

static PARALLEL_GROUPS: std::sync::Mutex<Vec<Option<ParallelGroup>>> =
    std::sync::Mutex::new(Vec::new());
static PARALLEL_GROUP_COUNTER: std::sync::atomic::AtomicI64 = std::sync::atomic::AtomicI64::new(0);

/// Creates a new parallel group and returns its identifier.
#[no_mangle]
pub extern "C" fn kodo_parallel_begin() -> i64 {
    let id = PARALLEL_GROUP_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    if let Ok(mut groups) = PARALLEL_GROUPS.lock() {
        #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
        let idx = id as usize;
        if groups.len() <= idx {
            groups.resize_with(idx + 1, || None);
        }
        groups[idx] = Some(ParallelGroup { tasks: Vec::new() });
    }
    id
}

/// Adds a task to a parallel group.
///
/// # Safety
///
/// When `env_size > 0`, the caller must ensure `env_ptr` points to
/// a readable buffer of at least `env_size` bytes.
#[no_mangle]
pub extern "C" fn kodo_parallel_spawn(group: i64, fn_ptr: i64, env_ptr: i64, env_size: i64) {
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let size = env_size as usize;
    let task = if size == 0 {
        // SAFETY: `fn_ptr` is a valid function pointer from Cranelift codegen.
        let func: extern "C" fn() = unsafe { std::mem::transmute(fn_ptr) };
        ParallelTask::Plain(func)
    } else {
        let mut env = vec![0u8; size];
        // SAFETY: caller guarantees `env_ptr` points to `env_size` readable bytes.
        unsafe {
            std::ptr::copy_nonoverlapping(env_ptr as *const u8, env.as_mut_ptr(), size);
        }
        // SAFETY: `fn_ptr` is a valid function pointer from Cranelift codegen.
        let func: extern "C" fn(i64) = unsafe { std::mem::transmute(fn_ptr) };
        ParallelTask::WithEnv { func, env }
    };
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let idx = group as usize;
    if let Ok(mut groups) = PARALLEL_GROUPS.lock() {
        if let Some(Some(g)) = groups.get_mut(idx) {
            g.tasks.push(task);
        }
    }
}

/// Joins all tasks in a parallel group using [`std::thread::scope`].
#[no_mangle]
pub extern "C" fn kodo_parallel_join(group: i64) {
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let idx = group as usize;
    let tasks = {
        if let Ok(mut groups) = PARALLEL_GROUPS.lock() {
            groups
                .get_mut(idx)
                .and_then(Option::take)
                .map(|g| g.tasks)
                .unwrap_or_default()
        } else {
            return;
        }
    };
    std::thread::scope(|s| {
        for task in &tasks {
            match task {
                ParallelTask::Plain(func) => {
                    let f = *func;
                    s.spawn(move || f());
                }
                ParallelTask::WithEnv { func, env } => {
                    let f = *func;
                    let ptr = env.as_ptr() as i64;
                    s.spawn(move || f(ptr));
                }
            }
        }
    });
}

/// Spawns a task by adding its function pointer to the task queue.
///
/// The task will be executed when the scheduler runs (at the end of `main`).
#[no_mangle]
pub extern "C" fn kodo_spawn_task(task: extern "C" fn()) {
    if let Ok(mut queue) = TASK_QUEUE.lock() {
        queue.push(Task::Plain(task));
    }
}

/// Spawns a task that carries a captured environment.
///
/// `fn_ptr` is a function that takes a single `i64` argument (a pointer to
/// the environment data). `env_ptr` points to the environment buffer in the
/// caller's stack frame and `env_size` is its size in bytes. The runtime
/// copies the environment so it remains valid when the task eventually runs.
///
/// # Safety
///
/// The caller must ensure that `env_ptr` points to a readable buffer of at
/// least `env_size` bytes.
#[no_mangle]
pub extern "C" fn kodo_spawn_task_with_env(fn_ptr: i64, env_ptr: i64, env_size: i64) {
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let size = env_size as usize;
    let mut env = vec![0u8; size];
    if size > 0 {
        // SAFETY: The caller guarantees `env_ptr` points to `env_size`
        // readable bytes (the captures packed on the caller's stack).
        unsafe {
            std::ptr::copy_nonoverlapping(env_ptr as *const u8, env.as_mut_ptr(), size);
        }
    }
    // SAFETY: `fn_ptr` is a valid function pointer produced by Cranelift
    // codegen with the `extern "C" fn(i64)` signature.
    let func: extern "C" fn(i64) = unsafe { std::mem::transmute(fn_ptr) };
    if let Ok(mut queue) = TASK_QUEUE.lock() {
        queue.push(Task::WithEnv { func, env });
    }
}

/// Runs all spawned tasks in FIFO order.
///
/// Called automatically by the runtime after `kodo_main` returns.
/// Tasks may spawn additional tasks, which are executed in subsequent
/// passes until the queue is empty.
#[no_mangle]
pub extern "C" fn kodo_run_scheduler() {
    loop {
        let tasks: Vec<Task> = {
            if let Ok(mut queue) = TASK_QUEUE.lock() {
                std::mem::take(&mut *queue)
            } else {
                break;
            }
        };
        if tasks.is_empty() {
            break;
        }
        for task in tasks {
            match task {
                Task::Plain(func) => func(),
                Task::WithEnv { func, env } => func(env.as_ptr() as i64),
            }
        }
    }
}

/// Legacy no-op spawn stub (kept for backwards compatibility).
#[no_mangle]
pub extern "C" fn kodo_spawn() {
    // Legacy stub — new code uses kodo_spawn_task.
}

/// Checks if a file exists at the given path.
///
/// Returns 1 if the file exists, 0 otherwise.
///
/// # Safety
///
/// `path_ptr` must point to `path_len` valid UTF-8 bytes.
#[no_mangle]
pub unsafe extern "C" fn kodo_file_exists(path_ptr: *const u8, path_len: usize) -> i64 {
    // SAFETY: caller guarantees valid UTF-8 bytes at path_ptr..path_ptr+path_len.
    let path_bytes = unsafe { std::slice::from_raw_parts(path_ptr, path_len) };
    let Ok(path_str) = std::str::from_utf8(path_bytes) else {
        return 0;
    };
    i64::from(std::path::Path::new(path_str).exists())
}

/// Reads a file into a heap-allocated string.
///
/// Returns 0 on success (Ok), 1 on error (Err). In both cases,
/// `out_ptr`/`out_len` are set to the content string or error message.
///
/// # Safety
///
/// `path_ptr` must point to `path_len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_file_read(
    path_ptr: *const u8,
    path_len: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) -> i64 {
    // SAFETY: caller guarantees valid UTF-8 bytes at path_ptr..path_ptr+path_len.
    let path_bytes = unsafe { std::slice::from_raw_parts(path_ptr, path_len) };
    let path_str = match std::str::from_utf8(path_bytes) {
        Ok(s) => s,
        Err(e) => {
            let msg = format!("invalid path: {e}");
            write_string_out(msg, out_ptr, out_len);
            return 1;
        }
    };
    match std::fs::read_to_string(path_str) {
        Ok(contents) => {
            write_string_out(contents, out_ptr, out_len);
            0
        }
        Err(e) => {
            let msg = format!("{e}");
            write_string_out(msg, out_ptr, out_len);
            1
        }
    }
}

/// Writes content to a file.
///
/// Returns 0 on success (Ok), 1 on error (Err). On error,
/// `out_ptr`/`out_len` are set to the error message.
///
/// # Safety
///
/// `path_ptr` must point to `path_len` valid UTF-8 bytes.
/// `content_ptr` must point to `content_len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_file_write(
    path_ptr: *const u8,
    path_len: usize,
    content_ptr: *const u8,
    content_len: usize,
    out_ptr: *mut *const u8,
    out_len: *mut usize,
) -> i64 {
    // SAFETY: caller guarantees valid UTF-8 bytes.
    let path_bytes = unsafe { std::slice::from_raw_parts(path_ptr, path_len) };
    let content_bytes = unsafe { std::slice::from_raw_parts(content_ptr, content_len) };
    let path_str = match std::str::from_utf8(path_bytes) {
        Ok(s) => s,
        Err(e) => {
            let msg = format!("invalid path: {e}");
            write_string_out(msg, out_ptr, out_len);
            return 1;
        }
    };
    match std::fs::write(path_str, content_bytes) {
        Ok(()) => 0,
        Err(e) => {
            let msg = format!("{e}");
            write_string_out(msg, out_ptr, out_len);
            1
        }
    }
}

/// Writes a Rust `String` to out-parameter pointers.
///
/// Leaks the string's bytes as a heap allocation, setting `out_ptr` and
/// `out_len` to point to the data. The caller is responsible for freeing.
///
/// # Safety
///
/// `out_ptr` and `out_len` must be valid writable pointers.
unsafe fn write_string_out(s: String, out_ptr: *mut *const u8, out_len: *mut usize) {
    let bytes = s.into_bytes().into_boxed_slice();
    let len = bytes.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    let ptr = Box::into_raw(bytes) as *const u8;
    // SAFETY: caller guarantees these are valid writable pointers.
    unsafe {
        *out_ptr = ptr;
        *out_len = len;
    }
}

/// Represents a heap-allocated dynamic list.
///
/// Each element is stored as an `i64` (values for Int, pointers for String).
/// This struct is never directly exposed to Kōdo code — the runtime manages
/// it through opaque pointer handles.
#[repr(C)]
struct KodoList {
    /// Pointer to the element array.
    data: *mut i64,
    /// Number of elements currently in the list.
    len: usize,
    /// Allocated capacity (number of i64 slots).
    capacity: usize,
}

/// Creates a new empty list.
///
/// Returns a pointer (as i64) to a heap-allocated `KodoList`.
#[no_mangle]
pub extern "C" fn kodo_list_new() -> i64 {
    let list = Box::new(KodoList {
        data: std::ptr::null_mut(),
        len: 0,
        capacity: 0,
    });
    // SAFETY: intentionally leaks so caller manages via opaque pointer. Freed by `kodo_list_free`.
    Box::into_raw(list) as i64
}

/// Pushes an element onto the end of a list.
///
/// Grows the backing array if needed (doubling strategy).
///
/// # Safety
///
/// `list_ptr` must be a valid pointer returned by `kodo_list_new`.
#[no_mangle]
pub unsafe extern "C" fn kodo_list_push(list_ptr: i64, value: i64) {
    #[allow(clippy::cast_possible_truncation)]
    let list = unsafe { &mut *(list_ptr as *mut KodoList) };
    if list.len == list.capacity {
        let new_cap = if list.capacity == 0 {
            4
        } else {
            list.capacity * 2
        };
        let new_layout = std::alloc::Layout::array::<i64>(new_cap);
        let Ok(layout) = new_layout else { return };
        let new_data = if list.data.is_null() {
            // SAFETY: layout is valid and non-zero size.
            #[allow(clippy::cast_ptr_alignment)]
            unsafe {
                std::alloc::alloc(layout).cast::<i64>()
            }
        } else {
            let old_layout_result = std::alloc::Layout::array::<i64>(list.capacity);
            let Ok(old_layout) = old_layout_result else {
                return;
            };
            // SAFETY: list.data was allocated with old_layout, new size >= old size.
            #[allow(clippy::cast_ptr_alignment)]
            unsafe {
                std::alloc::realloc(list.data.cast::<u8>(), old_layout, layout.size()).cast::<i64>()
            }
        };
        if new_data.is_null() {
            return; // allocation failed
        }
        list.data = new_data;
        list.capacity = new_cap;
    }
    // SAFETY: list.len < list.capacity, data is valid.
    unsafe { *list.data.add(list.len) = value };
    list.len += 1;
}

/// Returns the element at the given index, or 0 if out of bounds.
///
/// Returns a two-value result: (value, `is_some`) where `is_some` is 1 if the
/// index was valid, 0 otherwise. The values are written to out parameters.
///
/// # Safety
///
/// `list_ptr` must be a valid pointer returned by `kodo_list_new`.
/// `out_value` and `out_is_some` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_list_get(
    list_ptr: i64,
    index: i64,
    out_value: *mut i64,
    out_is_some: *mut i64,
) {
    #[allow(clippy::cast_possible_truncation)]
    let list = unsafe { &*(list_ptr as *const KodoList) };
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let idx = index as usize;
    if idx < list.len {
        // SAFETY: idx < len, data is valid.
        unsafe {
            *out_value = *list.data.add(idx);
            *out_is_some = 1;
        }
    } else {
        unsafe {
            *out_value = 0;
            *out_is_some = 0;
        }
    }
}

/// Returns the number of elements in the list.
///
/// # Safety
///
/// `list_ptr` must be a valid pointer returned by `kodo_list_new`.
#[no_mangle]
pub unsafe extern "C" fn kodo_list_length(list_ptr: i64) -> i64 {
    #[allow(clippy::cast_possible_truncation)]
    let list = unsafe { &*(list_ptr as *const KodoList) };
    #[allow(clippy::cast_possible_wrap)]
    let result = list.len as i64;
    result
}

/// Returns 1 if the list contains the given value, 0 otherwise.
///
/// Comparison is done by i64 equality (works for Int values).
///
/// # Safety
///
/// `list_ptr` must be a valid pointer returned by `kodo_list_new`.
#[no_mangle]
pub unsafe extern "C" fn kodo_list_contains(list_ptr: i64, value: i64) -> i64 {
    #[allow(clippy::cast_possible_truncation)]
    let list = unsafe { &*(list_ptr as *const KodoList) };
    for i in 0..list.len {
        // SAFETY: i < len, data is valid.
        if unsafe { *list.data.add(i) } == value {
            return 1;
        }
    }
    0
}

/// Splits a string by a separator and returns a `List<String>`.
///
/// Each resulting substring is allocated as a new (ptr, len) pair on the heap.
/// The list contains pointers to these string values.
///
/// The returned list stores each string as two consecutive i64 values (ptr, len),
/// but since our list holds single i64 elements, we actually return a list of
/// string pointers. Each string "pointer" is a pointer to a heap-allocated
/// (ptr: *const u8, len: usize) pair.
///
/// # Safety
///
/// Both pointer/length pairs must point to valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_string_split(
    hay_ptr: *const u8,
    hay_len: usize,
    sep_ptr: *const u8,
    sep_len: usize,
) -> i64 {
    let haystack = unsafe { std::slice::from_raw_parts(hay_ptr, hay_len) };
    let separator = unsafe { std::slice::from_raw_parts(sep_ptr, sep_len) };

    let list = kodo_list_new();

    if separator.is_empty() {
        // Empty separator: return the whole string as a single element.
        #[allow(clippy::cast_possible_wrap)]
        let pair = Box::new([hay_ptr as i64, hay_len as i64]);
        // SAFETY: intentionally leaks so the pair can be stored in the list.
        let pair_ptr = Box::into_raw(pair) as i64;
        // SAFETY: list is valid, just created above.
        unsafe { kodo_list_push(list, pair_ptr) };
        return list;
    }

    let mut start = 0;
    while start <= haystack.len() {
        // Find next occurrence of separator.
        let remaining = &haystack[start..];
        let found = remaining
            .windows(separator.len())
            .position(|w| w == separator);

        if let Some(pos) = found {
            // Allocate a (ptr, len) pair for this substring.
            let sub_ptr = unsafe { hay_ptr.add(start) };
            let sub_len = pos;
            #[allow(clippy::cast_possible_wrap)]
            let pair = Box::new([sub_ptr as i64, sub_len as i64]);
            // SAFETY: intentionally leaks so the pair can be stored in the list.
            let pair_ptr = Box::into_raw(pair) as i64;
            // SAFETY: list is valid.
            unsafe { kodo_list_push(list, pair_ptr) };
            start += pos + separator.len();
        } else {
            // Last segment.
            let sub_ptr = unsafe { hay_ptr.add(start) };
            let sub_len = haystack.len() - start;
            #[allow(clippy::cast_possible_wrap)]
            let pair = Box::new([sub_ptr as i64, sub_len as i64]);
            // SAFETY: intentionally leaks so the pair can be stored in the list.
            let pair_ptr = Box::into_raw(pair) as i64;
            // SAFETY: list is valid.
            unsafe { kodo_list_push(list, pair_ptr) };
            break;
        }
    }

    list
}

/// Represents a key-value pair in a hash map entry.
#[derive(Clone)]
#[repr(C)]
struct KodoMapEntry {
    /// The key (i64 value or pointer).
    key: i64,
    /// The value (i64 value or pointer).
    value: i64,
    /// Whether this entry is occupied.
    occupied: bool,
}

/// Represents a heap-allocated hash map.
///
/// Uses open addressing with linear probing for simplicity.
#[repr(C)]
struct KodoMap {
    /// Pointer to the entry array.
    entries: *mut KodoMapEntry,
    /// Number of occupied entries.
    len: usize,
    /// Total allocated capacity.
    capacity: usize,
}

/// Default initial capacity for a new map.
const MAP_INITIAL_CAPACITY: usize = 16;

/// Creates a new empty map.
///
/// Returns a pointer (as i64) to a heap-allocated `KodoMap`.
#[no_mangle]
pub extern "C" fn kodo_map_new() -> i64 {
    let entries = vec![
        KodoMapEntry {
            key: 0,
            value: 0,
            occupied: false,
        };
        MAP_INITIAL_CAPACITY
    ];
    let boxed = entries.into_boxed_slice();
    // SAFETY: intentionally leaks the entries array; ownership moves to KodoMap.
    let entries_ptr = Box::into_raw(boxed).cast::<KodoMapEntry>();
    let map = Box::new(KodoMap {
        entries: entries_ptr,
        len: 0,
        capacity: MAP_INITIAL_CAPACITY,
    });
    // SAFETY: intentionally leaks so caller manages via opaque pointer. Freed by `kodo_map_free`.
    Box::into_raw(map) as i64
}

/// Computes a simple hash for an i64 key.
fn map_hash(key: i64, capacity: usize) -> usize {
    // FNV-inspired mixing.
    #[allow(clippy::cast_sign_loss)]
    let k = key as u64;
    let mixed = k.wrapping_mul(0x517c_c1b7_2722_0a95);
    #[allow(clippy::cast_possible_truncation)]
    let index = mixed as usize;
    index % capacity
}

/// Inserts a key-value pair into the map, overwriting any existing entry with the same key.
///
/// # Safety
///
/// `map_ptr` must be a valid pointer returned by `kodo_map_new`.
#[no_mangle]
pub unsafe extern "C" fn kodo_map_insert(map_ptr: i64, key: i64, value: i64) {
    #[allow(clippy::cast_possible_truncation)]
    let map = unsafe { &mut *(map_ptr as *mut KodoMap) };

    // Grow if load factor > 0.75.
    if map.len * 4 >= map.capacity * 3 {
        map_grow(map);
    }

    let mut idx = map_hash(key, map.capacity);
    loop {
        // SAFETY: idx < capacity, entries is valid.
        let entry = unsafe { &mut *map.entries.add(idx) };
        if !entry.occupied {
            entry.key = key;
            entry.value = value;
            entry.occupied = true;
            map.len += 1;
            return;
        }
        if entry.key == key {
            entry.value = value;
            return;
        }
        idx = (idx + 1) % map.capacity;
    }
}

/// Grows the map's backing array by doubling capacity and rehashing all entries.
fn map_grow(map: &mut KodoMap) {
    let new_cap = map.capacity * 2;
    let new_entries = vec![
        KodoMapEntry {
            key: 0,
            value: 0,
            occupied: false,
        };
        new_cap
    ];
    let new_boxed = new_entries.into_boxed_slice();
    // SAFETY: intentionally leaks the new entries array; ownership moves to KodoMap.
    let new_ptr = Box::into_raw(new_boxed).cast::<KodoMapEntry>();

    // Rehash existing entries.
    for i in 0..map.capacity {
        // SAFETY: i < old capacity, entries is valid.
        let old_entry = unsafe { &*map.entries.add(i) };
        if old_entry.occupied {
            let mut idx = map_hash(old_entry.key, new_cap);
            loop {
                // SAFETY: idx < new_cap, new_ptr is valid.
                let new_entry = unsafe { &mut *new_ptr.add(idx) };
                if !new_entry.occupied {
                    new_entry.key = old_entry.key;
                    new_entry.value = old_entry.value;
                    new_entry.occupied = true;
                    break;
                }
                idx = (idx + 1) % new_cap;
            }
        }
    }

    // Free old entries.
    // SAFETY: entries was allocated as a Box<[KodoMapEntry]> with capacity elements.
    let _ = unsafe {
        Box::from_raw(std::ptr::slice_from_raw_parts_mut(
            map.entries,
            map.capacity,
        ))
    };
    map.entries = new_ptr;
    map.capacity = new_cap;
}

/// Gets the value for a given key.
///
/// Returns the value via out parameters. `out_is_some` is set to 1 if found, 0 otherwise.
///
/// # Safety
///
/// `map_ptr` must be a valid pointer returned by `kodo_map_new`.
/// `out_value` and `out_is_some` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_map_get(
    map_ptr: i64,
    key: i64,
    out_value: *mut i64,
    out_is_some: *mut i64,
) {
    #[allow(clippy::cast_possible_truncation)]
    let map = unsafe { &*(map_ptr as *const KodoMap) };
    let mut idx = map_hash(key, map.capacity);
    for _ in 0..map.capacity {
        // SAFETY: idx < capacity, entries is valid.
        let entry = unsafe { &*map.entries.add(idx) };
        if !entry.occupied {
            unsafe {
                *out_value = 0;
                *out_is_some = 0;
            }
            return;
        }
        if entry.key == key {
            unsafe {
                *out_value = entry.value;
                *out_is_some = 1;
            }
            return;
        }
        idx = (idx + 1) % map.capacity;
    }
    unsafe {
        *out_value = 0;
        *out_is_some = 0;
    }
}

/// Returns 1 if the map contains the given key, 0 otherwise.
///
/// # Safety
///
/// `map_ptr` must be a valid pointer returned by `kodo_map_new`.
#[no_mangle]
pub unsafe extern "C" fn kodo_map_contains_key(map_ptr: i64, key: i64) -> i64 {
    #[allow(clippy::cast_possible_truncation)]
    let map = unsafe { &*(map_ptr as *const KodoMap) };
    let mut idx = map_hash(key, map.capacity);
    for _ in 0..map.capacity {
        // SAFETY: idx < capacity, entries is valid.
        let entry = unsafe { &*map.entries.add(idx) };
        if !entry.occupied {
            return 0;
        }
        if entry.key == key {
            return 1;
        }
        idx = (idx + 1) % map.capacity;
    }
    0
}

/// Returns the number of entries in the map.
///
/// # Safety
///
/// `map_ptr` must be a valid pointer returned by `kodo_map_new`.
#[no_mangle]
pub unsafe extern "C" fn kodo_map_length(map_ptr: i64) -> i64 {
    #[allow(clippy::cast_possible_truncation)]
    let map = unsafe { &*(map_ptr as *const KodoMap) };
    #[allow(clippy::cast_possible_wrap)]
    let result = map.len as i64;
    result
}

/// Frees a heap-allocated string previously returned by runtime functions
/// (e.g. `kodo_string_concat`, `kodo_string_replace`, `kodo_int_to_string`).
///
/// Does nothing if `ptr` is null or `len` is zero.
///
/// # Safety
///
/// `ptr` must have been allocated by `Box::into_raw` on a `Box<[u8]>` of
/// exactly `len` bytes, or be null.
#[no_mangle]
pub unsafe extern "C" fn kodo_string_free(ptr: *mut u8, len: usize) {
    if ptr.is_null() || len == 0 {
        return;
    }
    // SAFETY: caller guarantees ptr was allocated via Box::into_raw on a
    // Box<[u8]> of exactly `len` bytes.
    let _ = unsafe { Box::from_raw(std::ptr::slice_from_raw_parts_mut(ptr, len)) };
}

/// Frees a heap-allocated `KodoList` and its backing data array.
///
/// Does nothing if `list_ptr` is zero (null handle).
///
/// # Safety
///
/// `list_ptr` must be a valid pointer returned by `kodo_list_new`, or zero.
/// After calling this function, the list pointer must not be used again.
#[no_mangle]
pub unsafe extern "C" fn kodo_list_free(list_ptr: i64) {
    if list_ptr == 0 {
        return;
    }
    // SAFETY: caller guarantees list_ptr was returned by kodo_list_new
    // (i.e. Box::into_raw on a Box<KodoList>).
    let list = unsafe { Box::from_raw(list_ptr as *mut KodoList) };
    if !list.data.is_null() && list.capacity > 0 {
        let layout = std::alloc::Layout::array::<i64>(list.capacity);
        if let Ok(layout) = layout {
            // SAFETY: list.data was allocated via std::alloc::alloc with this layout.
            unsafe { std::alloc::dealloc(list.data.cast::<u8>(), layout) };
        }
    }
    // list is dropped here, freeing the KodoList struct itself.
}

/// Frees a heap-allocated `KodoMap` and its backing entries array.
///
/// Does nothing if `map_ptr` is zero (null handle).
///
/// # Safety
///
/// `map_ptr` must be a valid pointer returned by `kodo_map_new`, or zero.
/// After calling this function, the map pointer must not be used again.
#[no_mangle]
pub unsafe extern "C" fn kodo_map_free(map_ptr: i64) {
    if map_ptr == 0 {
        return;
    }
    // SAFETY: caller guarantees map_ptr was returned by kodo_map_new
    // (i.e. Box::into_raw on a Box<KodoMap>).
    let map = unsafe { Box::from_raw(map_ptr as *mut KodoMap) };
    if !map.entries.is_null() && map.capacity > 0 {
        // SAFETY: entries was allocated as a Box<[KodoMapEntry]> with capacity elements.
        let _ = unsafe {
            Box::from_raw(std::ptr::slice_from_raw_parts_mut(
                map.entries,
                map.capacity,
            ))
        };
    }
    // map is dropped here, freeing the KodoMap struct itself.
}

// ---------------------------------------------------------------------------
// Actor runtime builtins
// ---------------------------------------------------------------------------

/// Size of each field slot in actor state (8 bytes for i64 alignment).
const ACTOR_FIELD_SIZE: usize = 8;

/// Allocates a new actor state buffer of `state_size` bytes on the heap.
///
/// Returns an opaque handle (as i64) to the allocated buffer, or 0 if
/// `state_size` is non-positive.
///
/// The buffer is zero-initialized so all fields start at their default value.
#[no_mangle]
pub extern "C" fn kodo_actor_new(state_size: i64) -> i64 {
    if state_size <= 0 {
        return 0;
    }
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let size = state_size as usize;
    let buffer = vec![0u8; size].into_boxed_slice();
    // SAFETY: intentionally leaks so caller manages via opaque handle.
    // Freed by `kodo_actor_free`.
    let ptr = Box::into_raw(buffer);
    ptr.cast::<u8>() as i64
}

/// Reads an i64 value from the actor state buffer at the given byte offset.
///
/// Returns 0 if `actor_ptr` is zero (null handle) or the offset is negative.
///
/// # Safety
///
/// `actor_ptr` must be a valid pointer returned by `kodo_actor_new`, or zero.
/// `offset` must be aligned to 8 bytes and within the allocated buffer.
#[no_mangle]
pub extern "C" fn kodo_actor_get_field(actor_ptr: i64, offset: i64) -> i64 {
    if actor_ptr == 0 || offset < 0 {
        return 0;
    }
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let off = offset as usize;
    // SAFETY: caller guarantees actor_ptr points to a valid buffer of
    // sufficient size and offset is within bounds and 8-byte aligned.
    unsafe {
        let base = actor_ptr as *const u8;
        #[allow(clippy::cast_ptr_alignment)]
        let field_ptr = base.add(off).cast::<i64>();
        *field_ptr
    }
}

/// Writes an i64 value to the actor state buffer at the given byte offset.
///
/// Does nothing if `actor_ptr` is zero (null handle) or the offset is negative.
///
/// # Safety
///
/// `actor_ptr` must be a valid pointer returned by `kodo_actor_new`, or zero.
/// `offset` must be aligned to 8 bytes and within the allocated buffer.
#[no_mangle]
pub extern "C" fn kodo_actor_set_field(actor_ptr: i64, offset: i64, value: i64) {
    if actor_ptr == 0 || offset < 0 {
        return;
    }
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let off = offset as usize;
    // SAFETY: caller guarantees actor_ptr points to a valid buffer of
    // sufficient size and offset is within bounds and 8-byte aligned.
    unsafe {
        let base = actor_ptr as *mut u8;
        #[allow(clippy::cast_ptr_alignment)]
        let field_ptr = base.add(off).cast::<i64>();
        *field_ptr = value;
    }
}

/// Queues a message to an actor by spawning a task that calls the handler.
///
/// `handler_fn` is a function pointer to the compiled handler (which takes
/// `(actor_ptr: i64, arg: i64)` as parameters). The task is enqueued in the
/// scheduler and runs when `kodo_run_scheduler` is called.
///
/// Does nothing if `actor_ptr` is zero (null handle) or `handler_fn` is zero.
#[no_mangle]
pub extern "C" fn kodo_actor_send(actor_ptr: i64, handler_fn: i64, arg: i64) {
    if actor_ptr == 0 || handler_fn == 0 {
        return;
    }
    // Pack actor_ptr and arg into a two-element environment buffer.
    let env: [i64; 2] = [actor_ptr, arg];
    let env_ptr = env.as_ptr() as i64;
    #[allow(clippy::cast_possible_wrap)]
    let env_size = (ACTOR_FIELD_SIZE * 2) as i64;
    kodo_spawn_task_with_env(handler_fn, env_ptr, env_size);
}

/// Frees an actor state buffer previously allocated by `kodo_actor_new`.
///
/// Does nothing if `actor_ptr` is zero (null handle).
///
/// # Safety
///
/// `actor_ptr` must be a valid pointer returned by `kodo_actor_new`, or zero.
/// The `state_size` must match the value originally passed to `kodo_actor_new`.
/// After calling this function, the actor pointer must not be used again.
#[no_mangle]
pub extern "C" fn kodo_actor_free(actor_ptr: i64, state_size: i64) {
    if actor_ptr == 0 || state_size <= 0 {
        return;
    }
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    let size = state_size as usize;
    // SAFETY: caller guarantees actor_ptr was returned by kodo_actor_new
    // with exactly `state_size` bytes (i.e. Box::into_raw on a Box<[u8]>
    // of `size` bytes).
    let _ = unsafe {
        Box::from_raw(std::ptr::slice_from_raw_parts_mut(
            actor_ptr as *mut u8,
            size,
        ))
    };
}

// ---------------------------------------------------------------------------
// HTTP client builtins
// ---------------------------------------------------------------------------

/// Performs an HTTP GET request to the given URL.
///
/// On success, writes the response body to `out_ptr`/`out_len` and returns 0.
/// On error, writes the error message to `out_ptr`/`out_len` and returns -1.
/// The caller must free the output string with `kodo_string_free`.
///
/// # Safety
///
/// `url_ptr` must point to `url_len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_http_get(
    url_ptr: *const u8,
    url_len: usize,
    out_ptr: *mut *mut u8,
    out_len: *mut usize,
) -> i64 {
    if url_ptr.is_null() || out_ptr.is_null() || out_len.is_null() {
        return -1;
    }
    // SAFETY: caller guarantees url_ptr/url_len form a valid UTF-8 slice.
    let url_bytes = unsafe { std::slice::from_raw_parts(url_ptr, url_len) };
    let Ok(url) = std::str::from_utf8(url_bytes) else {
        write_string_out_mut("invalid URL: not UTF-8".to_string(), out_ptr, out_len);
        return -1;
    };
    match ureq::get(url).call() {
        Ok(response) => match response.into_body().read_to_string() {
            Ok(body) => {
                write_string_out_mut(body, out_ptr, out_len);
                0
            }
            Err(e) => {
                let msg = format!("failed to read response body: {e}");
                write_string_out_mut(msg, out_ptr, out_len);
                -1
            }
        },
        Err(e) => {
            let msg = format!("HTTP GET failed: {e}");
            write_string_out_mut(msg, out_ptr, out_len);
            -1
        }
    }
}

/// Performs an HTTP POST request to the given URL with the provided body.
///
/// On success, writes the response body to `out_ptr`/`out_len` and returns 0.
/// On error, writes the error message to `out_ptr`/`out_len` and returns -1.
/// The caller must free the output string with `kodo_string_free`.
///
/// # Safety
///
/// `url_ptr` must point to `url_len` valid UTF-8 bytes.
/// `body_ptr` must point to `body_len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_http_post(
    url_ptr: *const u8,
    url_len: usize,
    body_ptr: *const u8,
    body_len: usize,
    out_ptr: *mut *mut u8,
    out_len: *mut usize,
) -> i64 {
    if url_ptr.is_null() || body_ptr.is_null() || out_ptr.is_null() || out_len.is_null() {
        return -1;
    }
    // SAFETY: caller guarantees valid UTF-8 slices.
    let url_bytes = unsafe { std::slice::from_raw_parts(url_ptr, url_len) };
    let post_body = unsafe { std::slice::from_raw_parts(body_ptr, body_len) };
    let Ok(url) = std::str::from_utf8(url_bytes) else {
        write_string_out_mut("invalid URL: not UTF-8".to_string(), out_ptr, out_len);
        return -1;
    };
    let Ok(content) = std::str::from_utf8(post_body) else {
        write_string_out_mut("invalid body: not UTF-8".to_string(), out_ptr, out_len);
        return -1;
    };
    match ureq::post(url)
        .header("Content-Type", "application/json")
        .send(content)
    {
        Ok(response) => match response.into_body().read_to_string() {
            Ok(resp_body) => {
                write_string_out_mut(resp_body, out_ptr, out_len);
                0
            }
            Err(e) => {
                let msg = format!("failed to read response body: {e}");
                write_string_out_mut(msg, out_ptr, out_len);
                -1
            }
        },
        Err(e) => {
            let msg = format!("HTTP POST failed: {e}");
            write_string_out_mut(msg, out_ptr, out_len);
            -1
        }
    }
}

/// Writes a Rust `String` to mutable out-parameter pointers.
///
/// Similar to `write_string_out` but uses `*mut *mut u8` for compatibility
/// with builtins that return freeable strings.
///
/// # Safety
///
/// `out_ptr` and `out_len` must be valid writable pointers.
unsafe fn write_string_out_mut(s: String, out_ptr: *mut *mut u8, out_len: *mut usize) {
    let bytes = s.into_bytes().into_boxed_slice();
    let len = bytes.len();
    // SAFETY: intentionally leaks so caller manages memory via (ptr, len).
    // Freed by `kodo_string_free`.
    let raw_slice = Box::into_raw(bytes);
    unsafe {
        // SAFETY: raw_slice is a valid fat pointer from Box::into_raw.
        let ptr = (*raw_slice).as_mut_ptr();
        // SAFETY: caller guarantees these are valid writable pointers.
        *out_ptr = ptr;
        *out_len = len;
    }
}

// ---------------------------------------------------------------------------
// JSON parsing builtins
// ---------------------------------------------------------------------------

/// Parses a JSON string and returns an opaque handle to the parsed value.
///
/// Returns a non-zero handle on success, or 0 on parse error.
/// The handle must be freed with `kodo_json_free` when no longer needed.
///
/// # Safety
///
/// `str_ptr` must point to `str_len` valid UTF-8 bytes.
#[no_mangle]
pub unsafe extern "C" fn kodo_json_parse(str_ptr: *const u8, str_len: usize) -> i64 {
    if str_ptr.is_null() {
        return 0;
    }
    // SAFETY: caller guarantees str_ptr/str_len form a valid UTF-8 slice.
    let bytes = unsafe { std::slice::from_raw_parts(str_ptr, str_len) };
    let Ok(text) = std::str::from_utf8(bytes) else {
        return 0;
    };
    match serde_json::from_str::<serde_json::Value>(text) {
        Ok(value) => {
            let boxed = Box::new(value);
            // SAFETY: intentionally leaks so caller manages via opaque handle.
            // Freed by `kodo_json_free`.
            Box::into_raw(boxed) as i64
        }
        Err(_) => 0,
    }
}

/// Retrieves a string value from a parsed JSON object by key.
///
/// Returns 0 on success (writing the string to `out_ptr`/`out_len`),
/// or -1 if the key does not exist or the value is not a string.
/// The caller must free the output string with `kodo_string_free`.
///
/// # Safety
///
/// `handle` must be a valid handle returned by `kodo_json_parse`.
/// `key_ptr` must point to `key_len` valid UTF-8 bytes.
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_json_get_string(
    handle: i64,
    key_ptr: *const u8,
    key_len: usize,
    out_ptr: *mut *mut u8,
    out_len: *mut usize,
) -> i64 {
    if handle == 0 || key_ptr.is_null() || out_ptr.is_null() || out_len.is_null() {
        return -1;
    }
    // SAFETY: caller guarantees handle is a valid pointer from kodo_json_parse.
    let value = unsafe { &*(handle as *const serde_json::Value) };
    // SAFETY: caller guarantees key_ptr/key_len form a valid UTF-8 slice.
    let key_bytes = unsafe { std::slice::from_raw_parts(key_ptr, key_len) };
    let Ok(key) = std::str::from_utf8(key_bytes) else {
        return -1;
    };
    match value.get(key) {
        Some(serde_json::Value::String(s)) => {
            write_string_out_mut(s.clone(), out_ptr, out_len);
            0
        }
        _ => -1,
    }
}

/// Retrieves an integer value from a parsed JSON object by key.
///
/// Returns the integer value if the key exists and the value is a number
/// that fits in i64. Returns 0 if the key does not exist or the value
/// is not an integer (callers should use `kodo_json_get_string` for
/// type-safe access).
///
/// # Safety
///
/// `handle` must be a valid handle returned by `kodo_json_parse`.
/// `key_ptr` must point to `key_len` valid UTF-8 bytes.
#[no_mangle]
#[allow(clippy::similar_names)]
pub unsafe extern "C" fn kodo_json_get_int(handle: i64, key_ptr: *const u8, key_len: usize) -> i64 {
    if handle == 0 || key_ptr.is_null() {
        return 0;
    }
    // SAFETY: caller guarantees handle is a valid pointer from kodo_json_parse.
    let value = unsafe { &*(handle as *const serde_json::Value) };
    // SAFETY: caller guarantees key_ptr/key_len form a valid UTF-8 slice.
    let key_bytes = unsafe { std::slice::from_raw_parts(key_ptr, key_len) };
    let Ok(key) = std::str::from_utf8(key_bytes) else {
        return 0;
    };
    match value.get(key) {
        Some(serde_json::Value::Number(n)) => n.as_i64().unwrap_or(0),
        _ => 0,
    }
}

/// Frees a parsed JSON value previously returned by `kodo_json_parse`.
///
/// Does nothing if `handle` is 0 (null handle).
///
/// # Safety
///
/// `handle` must be a valid handle returned by `kodo_json_parse`, or 0.
/// After calling this function, the handle must not be used again.
#[no_mangle]
pub unsafe extern "C" fn kodo_json_free(handle: i64) {
    if handle == 0 {
        return;
    }
    // SAFETY: caller guarantees handle was returned by kodo_json_parse
    // (i.e. Box::into_raw on a Box<serde_json::Value>).
    let _ = unsafe { Box::from_raw(handle as *mut serde_json::Value) };
}

// Time builtins
/// Returns the current Unix timestamp in seconds.
#[no_mangle]
pub extern "C" fn kodo_time_now() -> i64 {
    let d = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    i64::try_from(d.as_secs()).unwrap_or(i64::MAX)
}
/// Returns the current Unix timestamp in milliseconds.
#[no_mangle]
pub extern "C" fn kodo_time_now_ms() -> i64 {
    let d = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    i64::try_from(d.as_millis()).unwrap_or(i64::MAX)
}
/// Formats a Unix timestamp as ISO 8601 UTC string.
/// # Safety
/// `out_ptr` and `out_len` must be valid writable pointers.
#[no_mangle]
pub unsafe extern "C" fn kodo_time_format(
    timestamp: i64,
    out_ptr: *mut *mut u8,
    out_len: *mut usize,
) {
    const SECS_PER_MIN: u64 = 60;
    const SECS_PER_HOUR: u64 = 3600;
    const SECS_PER_DAY: u64 = 86400;
    if out_ptr.is_null() || out_len.is_null() {
        return;
    }
    #[allow(clippy::cast_sign_loss)]
    let secs = if timestamp < 0 { 0 } else { timestamp as u64 };
    let days_since_epoch = secs / SECS_PER_DAY;
    let time_of_day = secs % SECS_PER_DAY;
    let hour = time_of_day / SECS_PER_HOUR;
    let minute = (time_of_day % SECS_PER_HOUR) / SECS_PER_MIN;
    let second = time_of_day % SECS_PER_MIN;
    #[allow(clippy::cast_possible_wrap)]
    let z = days_since_epoch as i64 + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    #[allow(clippy::cast_sign_loss)]
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    #[allow(clippy::cast_possible_wrap)]
    let y_raw = yoe as i64 + era * 400;
    #[allow(clippy::cast_sign_loss)]
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { y_raw + 1 } else { y_raw };
    let formatted = format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}Z");
    unsafe { write_string_out_mut(formatted, out_ptr, out_len) };
}
/// Returns elapsed milliseconds since start timestamp.
#[no_mangle]
pub extern "C" fn kodo_time_elapsed_ms(start_ms: i64) -> i64 {
    let now = kodo_time_now_ms();
    let diff = now - start_ms;
    if diff < 0 {
        0
    } else {
        diff
    }
}
// Environment builtins
/// Gets an environment variable value.
/// # Safety
/// `key_ptr` must point to valid UTF-8. `out_ptr` and `out_len` must be valid.
#[no_mangle]
pub unsafe extern "C" fn kodo_env_get(
    key_ptr: *const u8,
    key_len: usize,
    out_ptr: *mut *mut u8,
    out_len: *mut usize,
) {
    if out_ptr.is_null() || out_len.is_null() {
        return;
    }
    if key_ptr.is_null() {
        unsafe { write_string_out_mut(String::new(), out_ptr, out_len) };
        return;
    }
    let key =
        unsafe { std::str::from_utf8_unchecked(std::slice::from_raw_parts(key_ptr, key_len)) };
    let val = std::env::var(key).unwrap_or_default();
    unsafe { write_string_out_mut(val, out_ptr, out_len) };
}
/// Sets an environment variable.
/// # Safety
/// `key_ptr` and `val_ptr` must point to valid UTF-8.
#[no_mangle]
pub unsafe extern "C" fn kodo_env_set(
    key_ptr: *const u8,
    key_len: usize,
    val_ptr: *const u8,
    val_len: usize,
) {
    if key_ptr.is_null() || val_ptr.is_null() {
        return;
    }
    let key =
        unsafe { std::str::from_utf8_unchecked(std::slice::from_raw_parts(key_ptr, key_len)) };
    let val =
        unsafe { std::str::from_utf8_unchecked(std::slice::from_raw_parts(val_ptr, val_len)) };
    unsafe { std::env::set_var(key, val) };
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn kodo_print_int_does_not_panic() {
        kodo_print_int(42);
    }

    #[test]
    fn kodo_println_does_not_panic() {
        let msg = "hello test";
        // SAFETY: msg is a valid UTF-8 string slice.
        unsafe { kodo_println(msg.as_ptr(), msg.len()) };
    }

    #[test]
    fn kodo_spawn_does_not_panic() {
        kodo_spawn();
    }

    #[test]
    fn kodo_print_does_not_panic() {
        let msg = "no newline";
        // SAFETY: msg is a valid UTF-8 string slice.
        unsafe { kodo_print(msg.as_ptr(), msg.len()) };
    }

    #[test]
    fn kodo_abs_works() {
        assert_eq!(kodo_abs(42), 42);
        assert_eq!(kodo_abs(-42), 42);
        assert_eq!(kodo_abs(0), 0);
    }

    #[test]
    fn kodo_min_works() {
        assert_eq!(kodo_min(3, 7), 3);
        assert_eq!(kodo_min(7, 3), 3);
        assert_eq!(kodo_min(5, 5), 5);
    }

    #[test]
    fn kodo_max_works() {
        assert_eq!(kodo_max(3, 7), 7);
        assert_eq!(kodo_max(7, 3), 7);
        assert_eq!(kodo_max(5, 5), 5);
    }

    #[test]
    fn kodo_clamp_works() {
        assert_eq!(kodo_clamp(5, 1, 10), 5);
        assert_eq!(kodo_clamp(-5, 1, 10), 1);
        assert_eq!(kodo_clamp(15, 1, 10), 10);
    }

    #[test]
    fn kodo_string_length_works() {
        let s = "hello";
        // SAFETY: s is a valid string slice.
        assert_eq!(kodo_string_length(s.as_ptr(), s.len()), 5);
    }

    #[test]
    fn kodo_spawn_task_and_scheduler() {
        use std::sync::atomic::{AtomicI64, Ordering};
        static COUNTER: AtomicI64 = AtomicI64::new(0);

        extern "C" fn increment_counter() {
            COUNTER.fetch_add(1, Ordering::SeqCst);
        }

        COUNTER.store(0, Ordering::SeqCst);
        kodo_spawn_task(increment_counter);
        kodo_spawn_task(increment_counter);
        assert_eq!(COUNTER.load(Ordering::SeqCst), 0, "tasks not yet run");
        kodo_run_scheduler();
        assert_eq!(COUNTER.load(Ordering::SeqCst), 2, "both tasks ran");
    }

    #[test]
    fn kodo_spawn_task_with_env_and_scheduler() {
        use std::sync::atomic::{AtomicI64, Ordering};
        static RESULT: AtomicI64 = AtomicI64::new(0);

        extern "C" fn add_env_value(env_ptr: i64) {
            // SAFETY: env_ptr points to an i64 value packed by the test.
            let val = unsafe { *(env_ptr as *const i64) };
            RESULT.fetch_add(val, Ordering::SeqCst);
        }

        RESULT.store(0, Ordering::SeqCst);

        // Pack an i64 value (42) as the environment.
        let env_val: i64 = 42;
        let env_ptr = std::ptr::addr_of!(env_val) as i64;
        let env_size = std::mem::size_of::<i64>() as i64;

        kodo_spawn_task_with_env(add_env_value as *const () as i64, env_ptr, env_size);
        assert_eq!(RESULT.load(Ordering::SeqCst), 0, "task not yet run");
        kodo_run_scheduler();
        assert_eq!(RESULT.load(Ordering::SeqCst), 42, "task read env value");
    }

    #[test]
    fn kodo_spawn_task_with_env_multiple_captures() {
        use std::sync::atomic::{AtomicI64, Ordering};
        static SUM: AtomicI64 = AtomicI64::new(0);

        extern "C" fn sum_two_captures(env_ptr: i64) {
            // SAFETY: env_ptr points to two consecutive i64 values.
            let a = unsafe { *(env_ptr as *const i64) };
            let b = unsafe { *((env_ptr as *const i64).add(1)) };
            SUM.store(a + b, Ordering::SeqCst);
        }

        SUM.store(0, Ordering::SeqCst);

        let env: [i64; 2] = [10, 32];
        let env_ptr = env.as_ptr() as i64;
        let env_size = (std::mem::size_of::<i64>() * 2) as i64;

        kodo_spawn_task_with_env(sum_two_captures as *const () as i64, env_ptr, env_size);
        kodo_run_scheduler();
        assert_eq!(SUM.load(Ordering::SeqCst), 42, "task summed both captures");
    }

    #[test]
    fn kodo_string_contains_works() {
        let hay = "hello world";
        let needle = "world";
        // SAFETY: both are valid string slices.
        let result =
            unsafe { kodo_string_contains(hay.as_ptr(), hay.len(), needle.as_ptr(), needle.len()) };
        assert_eq!(result, 1);

        let missing = "xyz";
        let result = unsafe {
            kodo_string_contains(hay.as_ptr(), hay.len(), missing.as_ptr(), missing.len())
        };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_string_starts_with_works() {
        let s = "hello world";
        let prefix = "hello";
        let result =
            unsafe { kodo_string_starts_with(s.as_ptr(), s.len(), prefix.as_ptr(), prefix.len()) };
        assert_eq!(result, 1);

        let bad = "world";
        let result =
            unsafe { kodo_string_starts_with(s.as_ptr(), s.len(), bad.as_ptr(), bad.len()) };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_string_ends_with_works() {
        let s = "hello world";
        let suffix = "world";
        let result =
            unsafe { kodo_string_ends_with(s.as_ptr(), s.len(), suffix.as_ptr(), suffix.len()) };
        assert_eq!(result, 1);

        let bad = "hello";
        let result = unsafe { kodo_string_ends_with(s.as_ptr(), s.len(), bad.as_ptr(), bad.len()) };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_string_trim_works() {
        let s = "  hello  ";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: s is a valid string slice, out_ptr/out_len are valid.
        unsafe { kodo_string_trim(s.as_ptr(), s.len(), &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "hello");
    }

    #[test]
    fn kodo_string_to_upper_works() {
        let s = "hello";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: s is a valid string slice.
        unsafe { kodo_string_to_upper(s.as_ptr(), s.len(), &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "HELLO");
    }

    #[test]
    fn kodo_string_to_lower_works() {
        let s = "HELLO";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: s is a valid string slice.
        unsafe { kodo_string_to_lower(s.as_ptr(), s.len(), &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "hello");
    }

    #[test]
    fn kodo_string_substring_works() {
        let s = "hello world";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: s is a valid string slice.
        unsafe { kodo_string_substring(s.as_ptr(), s.len(), 0, 5, &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "hello");
    }

    #[test]
    fn kodo_int_to_string_works() {
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: out_ptr/out_len are valid writable pointers.
        unsafe { kodo_int_to_string(42, &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "42");
    }

    #[test]
    fn kodo_int_to_float64_works() {
        assert!((kodo_int_to_float64(42) - 42.0).abs() < f64::EPSILON);
    }

    #[test]
    fn kodo_float64_to_string_works() {
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: out_ptr/out_len are valid writable pointers.
        unsafe { kodo_float64_to_string(3.14, &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert!(std::str::from_utf8(result).unwrap().starts_with("3.14"));
    }

    #[test]
    fn kodo_float64_to_int_works() {
        assert_eq!(kodo_float64_to_int(3.7), 3);
        assert_eq!(kodo_float64_to_int(-2.9), -2);
    }

    #[test]
    fn kodo_file_exists_works() {
        // Cargo.toml always exists relative to the crate root.
        let existing = "Cargo.toml";
        // SAFETY: existing is a valid UTF-8 string slice.
        let result = unsafe { kodo_file_exists(existing.as_ptr(), existing.len()) };
        assert_eq!(result, 1);

        let missing = "definitely_nonexistent_file_xyz.ko";
        // SAFETY: missing is a valid UTF-8 string slice.
        let result = unsafe { kodo_file_exists(missing.as_ptr(), missing.len()) };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_file_read_works() {
        let path = "Cargo.toml";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: path is a valid string, out_ptr/out_len are valid pointers.
        let status =
            unsafe { kodo_file_read(path.as_ptr(), path.len(), &mut out_ptr, &mut out_len) };
        assert_eq!(status, 0, "expected Ok");
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        let content = std::str::from_utf8(result).unwrap();
        assert!(content.contains("[package]"));
    }

    #[test]
    fn kodo_file_read_missing_returns_error() {
        let path = "nonexistent_xyz.txt";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: path is a valid string, out_ptr/out_len are valid pointers.
        let status =
            unsafe { kodo_file_read(path.as_ptr(), path.len(), &mut out_ptr, &mut out_len) };
        assert_eq!(status, 1, "expected Err");
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        let msg = std::str::from_utf8(result).unwrap();
        assert!(!msg.is_empty());
    }

    #[test]
    fn kodo_file_write_and_read_roundtrip() {
        let path = "/tmp/kodo_test_file_write.txt";
        let content = "hello from kodo";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: all pointers are valid.
        let status = unsafe {
            kodo_file_write(
                path.as_ptr(),
                path.len(),
                content.as_ptr(),
                content.len(),
                &mut out_ptr,
                &mut out_len,
            )
        };
        assert_eq!(status, 0, "expected write Ok");

        // Read it back.
        let mut read_ptr: *const u8 = std::ptr::null();
        let mut read_len: usize = 0;
        let status =
            unsafe { kodo_file_read(path.as_ptr(), path.len(), &mut read_ptr, &mut read_len) };
        assert_eq!(status, 0, "expected read Ok");
        let result = unsafe { std::slice::from_raw_parts(read_ptr, read_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), content);

        // Clean up.
        let _ = std::fs::remove_file(path);
    }

    #[test]
    fn kodo_list_new_and_push() {
        let list = kodo_list_new();
        assert_ne!(list, 0);
        unsafe { kodo_list_push(list, 42) };
        assert_eq!(unsafe { kodo_list_length(list) }, 1);
        unsafe { kodo_list_push(list, 99) };
        assert_eq!(unsafe { kodo_list_length(list) }, 2);
    }

    #[test]
    fn kodo_list_get_works() {
        let list = kodo_list_new();
        unsafe {
            kodo_list_push(list, 10);
            kodo_list_push(list, 20);
            kodo_list_push(list, 30);
        }
        let mut value: i64 = 0;
        let mut is_some: i64 = 0;
        unsafe { kodo_list_get(list, 0, &mut value, &mut is_some) };
        assert_eq!(is_some, 1);
        assert_eq!(value, 10);

        unsafe { kodo_list_get(list, 2, &mut value, &mut is_some) };
        assert_eq!(is_some, 1);
        assert_eq!(value, 30);

        unsafe { kodo_list_get(list, 5, &mut value, &mut is_some) };
        assert_eq!(is_some, 0);
    }

    #[test]
    fn kodo_list_contains_works() {
        let list = kodo_list_new();
        unsafe {
            kodo_list_push(list, 10);
            kodo_list_push(list, 20);
        }
        assert_eq!(unsafe { kodo_list_contains(list, 10) }, 1);
        assert_eq!(unsafe { kodo_list_contains(list, 20) }, 1);
        assert_eq!(unsafe { kodo_list_contains(list, 30) }, 0);
    }

    #[test]
    fn kodo_list_grows_dynamically() {
        let list = kodo_list_new();
        for i in 0..100 {
            unsafe { kodo_list_push(list, i) };
        }
        assert_eq!(unsafe { kodo_list_length(list) }, 100);
        let mut value: i64 = 0;
        let mut is_some: i64 = 0;
        unsafe { kodo_list_get(list, 99, &mut value, &mut is_some) };
        assert_eq!(is_some, 1);
        assert_eq!(value, 99);
    }

    #[test]
    fn kodo_string_split_works() {
        let s = "hello,world,foo";
        let sep = ",";
        let list = unsafe { kodo_string_split(s.as_ptr(), s.len(), sep.as_ptr(), sep.len()) };
        assert_eq!(unsafe { kodo_list_length(list) }, 3);
    }

    #[test]
    fn kodo_map_new_and_insert() {
        let map = kodo_map_new();
        assert_ne!(map, 0);
        unsafe { kodo_map_insert(map, 1, 100) };
        assert_eq!(unsafe { kodo_map_length(map) }, 1);
    }

    #[test]
    fn kodo_map_get_works() {
        let map = kodo_map_new();
        unsafe {
            kodo_map_insert(map, 1, 100);
            kodo_map_insert(map, 2, 200);
        }
        let mut value: i64 = 0;
        let mut is_some: i64 = 0;
        unsafe { kodo_map_get(map, 1, &mut value, &mut is_some) };
        assert_eq!(is_some, 1);
        assert_eq!(value, 100);

        unsafe { kodo_map_get(map, 2, &mut value, &mut is_some) };
        assert_eq!(is_some, 1);
        assert_eq!(value, 200);

        unsafe { kodo_map_get(map, 3, &mut value, &mut is_some) };
        assert_eq!(is_some, 0);
    }

    #[test]
    fn kodo_map_contains_key_works() {
        let map = kodo_map_new();
        unsafe {
            kodo_map_insert(map, 42, 1);
        }
        assert_eq!(unsafe { kodo_map_contains_key(map, 42) }, 1);
        assert_eq!(unsafe { kodo_map_contains_key(map, 99) }, 0);
    }

    #[test]
    fn kodo_map_overwrite_existing() {
        let map = kodo_map_new();
        unsafe {
            kodo_map_insert(map, 1, 100);
            kodo_map_insert(map, 1, 200);
        }
        assert_eq!(unsafe { kodo_map_length(map) }, 1);
        let mut value: i64 = 0;
        let mut is_some: i64 = 0;
        unsafe { kodo_map_get(map, 1, &mut value, &mut is_some) };
        assert_eq!(value, 200);
    }

    #[test]
    fn kodo_map_grows_dynamically() {
        let map = kodo_map_new();
        for i in 0..100 {
            unsafe { kodo_map_insert(map, i, i * 10) };
        }
        assert_eq!(unsafe { kodo_map_length(map) }, 100);
        let mut value: i64 = 0;
        let mut is_some: i64 = 0;
        unsafe { kodo_map_get(map, 50, &mut value, &mut is_some) };
        assert_eq!(is_some, 1);
        assert_eq!(value, 500);
    }

    #[test]
    fn kodo_string_concat_works() {
        let a = "hello ";
        let b = "world";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: both are valid string slices.
        unsafe {
            kodo_string_concat(
                a.as_ptr(),
                a.len(),
                b.as_ptr(),
                b.len(),
                &mut out_ptr,
                &mut out_len,
            );
        }
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "hello world");
    }

    #[test]
    fn kodo_string_concat_empty() {
        let a = "";
        let b = "world";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: both are valid string slices.
        unsafe {
            kodo_string_concat(
                a.as_ptr(),
                a.len(),
                b.as_ptr(),
                b.len(),
                &mut out_ptr,
                &mut out_len,
            );
        }
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "world");
    }

    #[test]
    fn kodo_string_index_of_works() {
        let hay = "hello world";
        let needle = "world";
        // SAFETY: both are valid string slices.
        let result =
            unsafe { kodo_string_index_of(hay.as_ptr(), hay.len(), needle.as_ptr(), needle.len()) };
        assert_eq!(result, 6);
    }

    #[test]
    fn kodo_string_index_of_not_found() {
        let hay = "hello world";
        let needle = "xyz";
        // SAFETY: both are valid string slices.
        let result =
            unsafe { kodo_string_index_of(hay.as_ptr(), hay.len(), needle.as_ptr(), needle.len()) };
        assert_eq!(result, -1);
    }

    #[test]
    fn kodo_string_index_of_empty_needle() {
        let hay = "hello";
        let needle = "";
        // SAFETY: both are valid string slices.
        let result =
            unsafe { kodo_string_index_of(hay.as_ptr(), hay.len(), needle.as_ptr(), needle.len()) };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_string_replace_works() {
        let hay = "hello world";
        let pattern = "world";
        let replacement = "kodo";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: all are valid string slices.
        unsafe {
            kodo_string_replace(
                hay.as_ptr(),
                hay.len(),
                pattern.as_ptr(),
                pattern.len(),
                replacement.as_ptr(),
                replacement.len(),
                &mut out_ptr,
                &mut out_len,
            );
        }
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "hello kodo");
    }

    #[test]
    fn kodo_string_replace_multiple() {
        let hay = "aXbXc";
        let pattern = "X";
        let replacement = "YY";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: all are valid string slices.
        unsafe {
            kodo_string_replace(
                hay.as_ptr(),
                hay.len(),
                pattern.as_ptr(),
                pattern.len(),
                replacement.as_ptr(),
                replacement.len(),
                &mut out_ptr,
                &mut out_len,
            );
        }
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "aYYbYYc");
    }

    #[test]
    fn kodo_string_replace_empty_pattern() {
        let hay = "hello";
        let pattern = "";
        let replacement = "X";
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: all are valid string slices.
        unsafe {
            kodo_string_replace(
                hay.as_ptr(),
                hay.len(),
                pattern.as_ptr(),
                pattern.len(),
                replacement.as_ptr(),
                replacement.len(),
                &mut out_ptr,
                &mut out_len,
            );
        }
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "hello");
    }

    #[test]
    fn kodo_string_eq_equal_strings() {
        let a = "hello";
        let b = "hello";
        // SAFETY: both are valid string slices.
        let result = unsafe { kodo_string_eq(a.as_ptr(), a.len(), b.as_ptr(), b.len()) };
        assert_eq!(result, 1);
    }

    #[test]
    fn kodo_string_eq_different_same_length() {
        let a = "hello";
        let b = "world";
        // SAFETY: both are valid string slices.
        let result = unsafe { kodo_string_eq(a.as_ptr(), a.len(), b.as_ptr(), b.len()) };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_string_eq_different_lengths() {
        let a = "hi";
        let b = "hello";
        // SAFETY: both are valid string slices.
        let result = unsafe { kodo_string_eq(a.as_ptr(), a.len(), b.as_ptr(), b.len()) };
        assert_eq!(result, 0);
    }

    #[test]
    fn kodo_string_eq_empty_strings() {
        let a = "";
        let b = "";
        // SAFETY: both are valid (empty) string slices.
        let result = unsafe { kodo_string_eq(a.as_ptr(), a.len(), b.as_ptr(), b.len()) };
        assert_eq!(result, 1);
    }

    #[test]
    fn kodo_string_eq_one_empty() {
        let a = "hello";
        let b = "";
        // SAFETY: both are valid string slices.
        let result = unsafe { kodo_string_eq(a.as_ptr(), a.len(), b.as_ptr(), b.len()) };
        assert_eq!(result, 0);
    }

    // --- Memory free tests ---

    #[test]
    fn kodo_string_free_null_does_not_crash() {
        // SAFETY: null pointer is explicitly handled by kodo_string_free.
        unsafe { kodo_string_free(std::ptr::null_mut(), 0) };
        unsafe { kodo_string_free(std::ptr::null_mut(), 42) };
    }

    #[test]
    fn kodo_string_free_valid_allocation() {
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: both are valid string slices, out pointers are valid.
        unsafe {
            kodo_string_concat(
                "hello ".as_ptr(),
                6,
                "world".as_ptr(),
                5,
                &mut out_ptr,
                &mut out_len,
            );
        }
        assert_eq!(out_len, 11);
        // SAFETY: out_ptr was allocated by kodo_string_concat.
        unsafe { kodo_string_free(out_ptr as *mut u8, out_len) };
    }

    #[test]
    fn kodo_string_free_roundtrip_int_to_string() {
        let mut out_ptr: *const u8 = std::ptr::null();
        let mut out_len: usize = 0;
        // SAFETY: out pointers are valid.
        unsafe { kodo_int_to_string(12345, &mut out_ptr, &mut out_len) };
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "12345");
        // SAFETY: out_ptr was allocated by kodo_int_to_string.
        unsafe { kodo_string_free(out_ptr as *mut u8, out_len) };
    }

    #[test]
    fn kodo_list_free_null_does_not_crash() {
        // SAFETY: zero (null handle) is explicitly handled by kodo_list_free.
        unsafe { kodo_list_free(0) };
    }

    #[test]
    fn kodo_list_free_empty_list() {
        let list = kodo_list_new();
        assert_ne!(list, 0);
        // SAFETY: list was returned by kodo_list_new.
        unsafe { kodo_list_free(list) };
    }

    #[test]
    fn kodo_list_free_with_elements() {
        let list = kodo_list_new();
        // SAFETY: list is valid.
        unsafe {
            kodo_list_push(list, 10);
            kodo_list_push(list, 20);
            kodo_list_push(list, 30);
        }
        assert_eq!(unsafe { kodo_list_length(list) }, 3);
        // SAFETY: list was returned by kodo_list_new.
        unsafe { kodo_list_free(list) };
    }

    #[test]
    fn kodo_map_free_null_does_not_crash() {
        // SAFETY: zero (null handle) is explicitly handled by kodo_map_free.
        unsafe { kodo_map_free(0) };
    }

    #[test]
    fn kodo_map_free_empty_map() {
        let map = kodo_map_new();
        assert_ne!(map, 0);
        // SAFETY: map was returned by kodo_map_new.
        unsafe { kodo_map_free(map) };
    }

    #[test]
    fn kodo_map_free_with_entries() {
        let map = kodo_map_new();
        // SAFETY: map is valid.
        unsafe {
            kodo_map_insert(map, 1, 100);
            kodo_map_insert(map, 2, 200);
            kodo_map_insert(map, 3, 300);
        }
        assert_eq!(unsafe { kodo_map_length(map) }, 3);
        // SAFETY: map was returned by kodo_map_new.
        unsafe { kodo_map_free(map) };
    }

    #[test]
    fn kodo_map_free_after_grow() {
        let map = kodo_map_new();
        // Insert enough entries to trigger at least one grow.
        for i in 0..50 {
            // SAFETY: map is valid.
            unsafe { kodo_map_insert(map, i, i * 10) };
        }
        assert_eq!(unsafe { kodo_map_length(map) }, 50);
        // SAFETY: map was returned by kodo_map_new.
        unsafe { kodo_map_free(map) };
    }

    // --- JSON tests ---

    #[test]
    fn kodo_json_parse_valid() {
        let json = r#"{"name": "kodo", "version": 1}"#;
        // SAFETY: json is a valid string slice.
        let handle = unsafe { kodo_json_parse(json.as_ptr(), json.len()) };
        assert_ne!(handle, 0, "parse should succeed");
        // SAFETY: handle is valid.
        unsafe { kodo_json_free(handle) };
    }

    #[test]
    fn kodo_json_parse_invalid() {
        let bad = "not json {{{";
        // SAFETY: bad is a valid string slice.
        let handle = unsafe { kodo_json_parse(bad.as_ptr(), bad.len()) };
        assert_eq!(handle, 0, "parse should fail for invalid JSON");
    }

    #[test]
    fn kodo_json_parse_null_ptr() {
        // SAFETY: testing null pointer handling.
        let handle = unsafe { kodo_json_parse(std::ptr::null(), 0) };
        assert_eq!(handle, 0, "null pointer should return 0");
    }

    #[test]
    fn kodo_json_get_string_works() {
        let json = r#"{"name": "kodo", "lang": "rust"}"#;
        // SAFETY: json is a valid string slice.
        let handle = unsafe { kodo_json_parse(json.as_ptr(), json.len()) };
        assert_ne!(handle, 0);

        let key = "name";
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: handle and key are valid.
        let status = unsafe {
            kodo_json_get_string(handle, key.as_ptr(), key.len(), &mut out_ptr, &mut out_len)
        };
        assert_eq!(status, 0, "should find key 'name'");
        let result = unsafe { std::slice::from_raw_parts(out_ptr, out_len) };
        assert_eq!(std::str::from_utf8(result).unwrap(), "kodo");

        // SAFETY: handle is valid.
        unsafe { kodo_json_free(handle) };
    }

    #[test]
    fn kodo_json_get_string_missing_key() {
        let json = r#"{"name": "kodo"}"#;
        // SAFETY: json is a valid string slice.
        let handle = unsafe { kodo_json_parse(json.as_ptr(), json.len()) };
        assert_ne!(handle, 0);

        let key = "missing";
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: handle and key are valid.
        let status = unsafe {
            kodo_json_get_string(handle, key.as_ptr(), key.len(), &mut out_ptr, &mut out_len)
        };
        assert_eq!(status, -1, "missing key should return -1");

        // SAFETY: handle is valid.
        unsafe { kodo_json_free(handle) };
    }

    #[test]
    fn kodo_json_get_int_works() {
        let json = r#"{"count": 42, "name": "test"}"#;
        // SAFETY: json is a valid string slice.
        let handle = unsafe { kodo_json_parse(json.as_ptr(), json.len()) };
        assert_ne!(handle, 0);

        let key = "count";
        // SAFETY: handle and key are valid.
        let value = unsafe { kodo_json_get_int(handle, key.as_ptr(), key.len()) };
        assert_eq!(value, 42);

        // Non-integer key returns 0.
        let key2 = "name";
        let value2 = unsafe { kodo_json_get_int(handle, key2.as_ptr(), key2.len()) };
        assert_eq!(value2, 0);

        // SAFETY: handle is valid.
        unsafe { kodo_json_free(handle) };
    }

    #[test]
    fn kodo_json_free_null_handle() {
        // SAFETY: testing null handle, should be a no-op.
        unsafe { kodo_json_free(0) };
    }

    #[test]
    fn kodo_json_get_string_null_handle() {
        let key = "test";
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: testing null handle.
        let status =
            unsafe { kodo_json_get_string(0, key.as_ptr(), key.len(), &mut out_ptr, &mut out_len) };
        assert_eq!(status, -1);
    }

    #[test]
    fn kodo_json_get_int_null_handle() {
        let key = "test";
        // SAFETY: testing null handle.
        let value = unsafe { kodo_json_get_int(0, key.as_ptr(), key.len()) };
        assert_eq!(value, 0);
    }

    // --- HTTP tests ---

    #[test]
    fn kodo_http_get_invalid_url_returns_error() {
        let url = "not-a-valid-url";
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: url is a valid string slice, out pointers are valid.
        let status = unsafe { kodo_http_get(url.as_ptr(), url.len(), &mut out_ptr, &mut out_len) };
        assert_eq!(status, -1, "invalid URL should return -1");
        assert!(!out_ptr.is_null(), "error message should be written");
        assert!(out_len > 0, "error message should be non-empty");
        // Free the error message.
        // SAFETY: out_ptr was allocated by write_string_out_mut.
        unsafe { kodo_string_free(out_ptr, out_len) };
    }

    #[test]
    fn kodo_http_get_null_ptr_returns_error() {
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: testing null pointer handling.
        let status = unsafe { kodo_http_get(std::ptr::null(), 0, &mut out_ptr, &mut out_len) };
        assert_eq!(status, -1);
    }

    #[test]
    fn kodo_http_post_null_ptr_returns_error() {
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: testing null pointer handling.
        let status = unsafe {
            kodo_http_post(
                std::ptr::null(),
                0,
                std::ptr::null(),
                0,
                &mut out_ptr,
                &mut out_len,
            )
        };
        assert_eq!(status, -1);
    }

    #[test]
    fn kodo_http_post_invalid_url_returns_error() {
        let url = "not-a-valid-url";
        let body = r#"{"key": "value"}"#;
        let mut out_ptr: *mut u8 = std::ptr::null_mut();
        let mut out_len: usize = 0;
        // SAFETY: url and body are valid string slices, out pointers are valid.
        let status = unsafe {
            kodo_http_post(
                url.as_ptr(),
                url.len(),
                body.as_ptr(),
                body.len(),
                &mut out_ptr,
                &mut out_len,
            )
        };
        assert_eq!(status, -1, "invalid URL should return -1");
        assert!(!out_ptr.is_null(), "error message should be written");
        // Free the error message.
        // SAFETY: out_ptr was allocated by write_string_out_mut.
        unsafe { kodo_string_free(out_ptr, out_len) };
    }

    // --- Actor runtime tests ---

    #[test]
    fn kodo_actor_new_returns_nonzero_handle() {
        let handle = kodo_actor_new(16);
        assert_ne!(handle, 0);
        // Clean up.
        kodo_actor_free(handle, 16);
    }

    #[test]
    fn kodo_actor_new_zero_size_returns_zero() {
        assert_eq!(kodo_actor_new(0), 0);
        assert_eq!(kodo_actor_new(-1), 0);
    }

    #[test]
    fn kodo_actor_set_get_field_roundtrip() {
        let actor = kodo_actor_new(24); // 3 fields * 8 bytes
        assert_ne!(actor, 0);

        kodo_actor_set_field(actor, 0, 42);
        kodo_actor_set_field(actor, 8, 100);
        kodo_actor_set_field(actor, 16, -7);

        assert_eq!(kodo_actor_get_field(actor, 0), 42);
        assert_eq!(kodo_actor_get_field(actor, 8), 100);
        assert_eq!(kodo_actor_get_field(actor, 16), -7);

        kodo_actor_free(actor, 24);
    }

    #[test]
    fn kodo_actor_get_field_null_returns_zero() {
        assert_eq!(kodo_actor_get_field(0, 0), 0);
        assert_eq!(kodo_actor_get_field(0, 8), 0);
    }

    #[test]
    fn kodo_actor_set_field_null_does_not_crash() {
        kodo_actor_set_field(0, 0, 42);
        kodo_actor_set_field(0, 8, 99);
    }

    #[test]
    fn kodo_actor_send_queues_task() {
        use std::sync::atomic::{AtomicI64, Ordering};
        static ACTOR_RESULT: AtomicI64 = AtomicI64::new(0);

        extern "C" fn handler(env_ptr: i64) {
            // SAFETY: env_ptr points to [actor_ptr, arg] packed by kodo_actor_send.
            let actor_ptr = unsafe { *(env_ptr as *const i64) };
            let arg = unsafe { *((env_ptr as *const i64).add(1)) };
            // Read field 0 from actor state.
            let current = kodo_actor_get_field(actor_ptr, 0);
            kodo_actor_set_field(actor_ptr, 0, current + arg);
            ACTOR_RESULT.store(kodo_actor_get_field(actor_ptr, 0), Ordering::SeqCst);
        }

        ACTOR_RESULT.store(0, Ordering::SeqCst);

        let actor = kodo_actor_new(8);
        kodo_actor_set_field(actor, 0, 10);
        kodo_actor_send(actor, handler as *const () as i64, 5);

        // Task not yet run.
        assert_eq!(ACTOR_RESULT.load(Ordering::SeqCst), 0);

        kodo_run_scheduler();

        // Handler ran: 10 + 5 = 15.
        assert_eq!(ACTOR_RESULT.load(Ordering::SeqCst), 15);

        kodo_actor_free(actor, 8);
    }

    #[test]
    fn kodo_actor_send_null_does_not_crash() {
        extern "C" fn dummy(_env_ptr: i64) {}
        kodo_actor_send(0, dummy as *const () as i64, 0);
        kodo_actor_send(42, 0, 0);
    }

    #[test]
    fn kodo_actor_free_null_does_not_crash() {
        kodo_actor_free(0, 8);
        kodo_actor_free(0, 0);
    }

    #[test]
    fn kodo_actor_free_negative_size_does_not_crash() {
        kodo_actor_free(0, -1);
    }

    #[test]
    fn kodo_actor_fields_initialized_to_zero() {
        let actor = kodo_actor_new(16);
        assert_eq!(kodo_actor_get_field(actor, 0), 0);
        assert_eq!(kodo_actor_get_field(actor, 8), 0);
        kodo_actor_free(actor, 16);
    }

    #[test]
    fn time_now_pos() {
        assert!(kodo_time_now() > 0);
    }
    #[test]
    fn time_now_ms_pos() {
        assert!(kodo_time_now_ms() > 0);
    }
    #[test]
    fn time_fmt_epoch() {
        let mut p: *mut u8 = std::ptr::null_mut();
        let mut l: usize = 0;
        unsafe { kodo_time_format(0, &mut p, &mut l) };
        let s = unsafe { String::from_raw_parts(p, l, l) };
        assert_eq!(s, "1970-01-01T00:00:00Z");
    }
    #[test]
    fn time_fmt_known() {
        let mut p: *mut u8 = std::ptr::null_mut();
        let mut l: usize = 0;
        unsafe { kodo_time_format(1_705_321_800, &mut p, &mut l) };
        let s = unsafe { String::from_raw_parts(p, l, l) };
        assert_eq!(s, "2024-01-15T12:30:00Z");
    }
    #[test]
    fn time_elapsed_nonneg() {
        assert!(kodo_time_elapsed_ms(kodo_time_now_ms()) >= 0);
    }
    #[test]
    fn env_rt() {
        let (k, v) = ("KODO_T27", "hi");
        unsafe {
            kodo_env_set(k.as_ptr(), k.len(), v.as_ptr(), v.len());
        }
        let mut p: *mut u8 = std::ptr::null_mut();
        let mut l: usize = 0;
        unsafe {
            kodo_env_get(k.as_ptr(), k.len(), &mut p, &mut l);
        }
        let s = unsafe { String::from_raw_parts(p, l, l) };
        assert_eq!(s, "hi");
    }
    #[test]
    fn env_missing() {
        let k = "KODO_X99";
        let mut p: *mut u8 = std::ptr::null_mut();
        let mut l: usize = 0;
        unsafe {
            kodo_env_get(k.as_ptr(), k.len(), &mut p, &mut l);
        }
        assert_eq!(l, 0);
    }
    #[test]
    fn env_null() {
        unsafe {
            kodo_env_set(std::ptr::null(), 0, std::ptr::null(), 0);
        }
    }

    #[test]
    fn parallel_group_unique_ids() {
        let id1 = kodo_parallel_begin();
        let id2 = kodo_parallel_begin();
        assert_ne!(id1, id2);
    }

    #[test]
    fn parallel_empty_group_join() {
        let id = kodo_parallel_begin();
        kodo_parallel_join(id);
    }

    #[test]
    fn parallel_spawn_and_join() {
        use std::sync::atomic::{AtomicI64, Ordering};
        static COUNTER: AtomicI64 = AtomicI64::new(0);
        extern "C" fn inc() {
            COUNTER.fetch_add(1, Ordering::Relaxed);
        }
        COUNTER.store(0, Ordering::Relaxed);
        let g = kodo_parallel_begin();
        kodo_parallel_spawn(g, inc as *const () as i64, 0, 0);
        kodo_parallel_spawn(g, inc as *const () as i64, 0, 0);
        kodo_parallel_join(g);
        assert_eq!(COUNTER.load(Ordering::Relaxed), 2);
    }

    #[test]
    fn parallel_spawn_with_env() {
        use std::sync::atomic::{AtomicI64, Ordering};
        static RESULT: AtomicI64 = AtomicI64::new(0);
        extern "C" fn read_env(env: i64) {
            // SAFETY: env points to an i64 value.
            let val = unsafe { *(env as *const i64) };
            RESULT.store(val, Ordering::Relaxed);
        }
        RESULT.store(0, Ordering::Relaxed);
        let value: i64 = 42;
        let g = kodo_parallel_begin();
        kodo_parallel_spawn(
            g,
            read_env as *const () as i64,
            &value as *const i64 as i64,
            8,
        );
        kodo_parallel_join(g);
        assert_eq!(RESULT.load(Ordering::Relaxed), 42);
    }
}
